/// Ownership of every persisted key name declared on [StorageService]
/// (`const _…Key` / CloudSecretPrefs aliases) plus CloudSecretPrefs' own
/// credential keys. Each name is owned by exactly one store.
///
/// Frozen compatibility surface: do not rename a key. Later G3 slices
/// reassign ownership when a domain store is extracted; they must not
/// change the string.
enum StorageKeyStore {
  /// Residual keys still declared on StorageService.
  storageService,

  /// [CloudSecretPrefs] credential keys.
  cloudSecretPrefs,

  /// Home page defaults and remaining Home keys ([HomePrefs]).
  homePrefs,
}

class StorageKeyOwnership {
  StorageKeyOwnership._();

  /// Persisted name → owning store. The key set is the pin.
  static const Map<String, StorageKeyStore> byKey = {
    'explicitly_watched_series_v1': StorageKeyStore.storageService,
    'tracking_scrobble_targets': StorageKeyStore.storageService,
    'watch_progress_source': StorageKeyStore.storageService,
    'home_tick_sources': StorageKeyStore.homePrefs,
    'defaults_generation': StorageKeyStore.storageService,
    'real_debrid_endpoint': StorageKeyStore.storageService,
    'real_debrid_file_selection': StorageKeyStore.storageService,
    'torbox_api_key': StorageKeyStore.cloudSecretPrefs,
    'torbox_check_cache_before_search': StorageKeyStore.storageService,
    'real_debrid_integration_enabled': StorageKeyStore.storageService,
    'real_debrid_hidden_from_nav': StorageKeyStore.storageService,
    'rd_skip_blocked_torrents': StorageKeyStore.storageService,
    'torbox_integration_enabled': StorageKeyStore.storageService,
    'torbox_hidden_from_nav': StorageKeyStore.storageService,
    'premiumize_api_key': StorageKeyStore.cloudSecretPrefs,
    'premiumize_integration_enabled': StorageKeyStore.storageService,
    'premiumize_post_torrent_action': StorageKeyStore.storageService,
    'premiumize_check_cache_before_search': StorageKeyStore.storageService,
    'premiumize_hidden_from_nav': StorageKeyStore.storageService,
    'alldebrid_api_key': StorageKeyStore.cloudSecretPrefs,
    'alldebrid_integration_enabled': StorageKeyStore.storageService,
    'alldebrid_post_torrent_action': StorageKeyStore.storageService,
    'alldebrid_hidden_from_nav': StorageKeyStore.storageService,
    'pikpak_hidden_from_nav': StorageKeyStore.storageService,
    'post_torrent_action': StorageKeyStore.storageService,
    'torbox_post_torrent_action': StorageKeyStore.storageService,
    'pikpak_post_torrent_action': StorageKeyStore.storageService,
    'battery_opt_status_v1': StorageKeyStore.storageService,
    'video_resume_v1': StorageKeyStore.storageService,
    'playback_state_v1': StorageKeyStore.storageService,
    'continue_watching_v1': StorageKeyStore.storageService,
    'local_series_completion_v1': StorageKeyStore.storageService,
    'local_series_completion_calendar_checked_at_v1':
        StorageKeyStore.storageService,
    'local_series_completion_calendar_attempted_at_v1':
        StorageKeyStore.storageService,
    'finished_movies_v1': StorageKeyStore.storageService,
    'debrify_tv_start_random': StorageKeyStore.storageService,
    'debrify_tv_hide_seekbar': StorageKeyStore.storageService,
    'debrify_tv_show_watermark': StorageKeyStore.storageService,
    'debrify_tv_show_video_title': StorageKeyStore.storageService,
    'debrify_tv_hide_options': StorageKeyStore.storageService,
    'debrify_tv_hide_back_button': StorageKeyStore.storageService,
    'debrify_tv_avoid_nsfw': StorageKeyStore.storageService,
    'debrify_tv_provider': StorageKeyStore.storageService,
    'debrify_tv_random_start_percent': StorageKeyStore.storageService,
    'debrify_tv_channels': StorageKeyStore.storageService,
    'debrify_tv_filter_qualities': StorageKeyStore.storageService,
    'debrify_tv_filter_sizes': StorageKeyStore.storageService,
    'debrify_tv_external_notice_dismissed': StorageKeyStore.storageService,
    'home_default_source_type': StorageKeyStore.homePrefs,
    'home_default_addon_url': StorageKeyStore.homePrefs,
    'home_default_catalog_id': StorageKeyStore.homePrefs,
    'home_default_trakt_list_type': StorageKeyStore.homePrefs,
    'home_default_trakt_content_type': StorageKeyStore.homePrefs,
    'home_hide_provider_cards': StorageKeyStore.homePrefs,
    'home_continue_watching_enabled': StorageKeyStore.homePrefs,
    'home_cw_hold_to_quick_play': StorageKeyStore.homePrefs,
    'home_cw_merge_': StorageKeyStore.homePrefs,
    'home_favorites_open_folder': StorageKeyStore.homePrefs,
    'home_card_orientation': StorageKeyStore.homePrefs,
    'home_hide_card_titles_and_ratings': StorageKeyStore.homePrefs,
    'home_hide_catalog_addon_names': StorageKeyStore.homePrefs,
    'support_remote_config_cache_v1': StorageKeyStore.storageService,
    'dismissed_donation_campaign_ids_v1': StorageKeyStore.storageService,
    'startup_auto_launch_enabled': StorageKeyStore.storageService,
    'startup_channel_id': StorageKeyStore.storageService,
    'startup_stremio_tv_channel_id': StorageKeyStore.storageService,
    'startup_mode': StorageKeyStore.storageService,
    'startup_playlist_item_id': StorageKeyStore.storageService,
    'startup_continue_watching_item_id': StorageKeyStore.storageService,
    'startup_trakt_continue_watching_movie_id': StorageKeyStore.storageService,
    'startup_trakt_continue_watching_show_id': StorageKeyStore.storageService,
    'reddit_access_token': StorageKeyStore.storageService,
    'reddit_refresh_token': StorageKeyStore.storageService,
    'reddit_username': StorageKeyStore.storageService,
    'reddit_enabled': StorageKeyStore.storageService,
    'reddit_hidden_from_nav': StorageKeyStore.storageService,
    'reddit_last_subreddit': StorageKeyStore.storageService,
    'reddit_recent_subreddits': StorageKeyStore.storageService,
    'reddit_allow_nsfw': StorageKeyStore.storageService,
    'reddit_favorite_subreddits': StorageKeyStore.storageService,
    'reddit_default_subreddit': StorageKeyStore.storageService,
    'lemmy_instance': StorageKeyStore.storageService,
    'lemmy_allow_nsfw': StorageKeyStore.storageService,
    'lemmy_favorite_communities': StorageKeyStore.storageService,
    'lemmy_default_community': StorageKeyStore.storageService,
    'youtube_max_height': StorageKeyStore.storageService,
    'network_connect_patience': StorageKeyStore.storageService,
    'iptv_decoder_mode': StorageKeyStore.storageService,
    'network_buffer_size': StorageKeyStore.storageService,
    'update_auto_check_enabled': StorageKeyStore.storageService,
    'update_ignored_version': StorageKeyStore.storageService,
    'default_player_mode': StorageKeyStore.storageService,
    'external_player_preferred': StorageKeyStore.storageService,
    'external_player_custom_path': StorageKeyStore.storageService,
    'external_player_custom_name': StorageKeyStore.storageService,
    'external_player_custom_command': StorageKeyStore.storageService,
    'ios_external_player_preferred': StorageKeyStore.storageService,
    'ios_custom_scheme_template': StorageKeyStore.storageService,
    'linux_external_player_preferred': StorageKeyStore.storageService,
    'linux_custom_command': StorageKeyStore.storageService,
    'windows_external_player_preferred': StorageKeyStore.storageService,
    'windows_custom_command': StorageKeyStore.storageService,
    'player_default_aspect_index': StorageKeyStore.storageService,
    'player_default_aspect_index_tv': StorageKeyStore.storageService,
    'player_night_mode_index': StorageKeyStore.storageService,
    'player_system_audio_effects': StorageKeyStore.storageService,
    'player_start_portrait': StorageKeyStore.storageService,
    'movie_completion_threshold': StorageKeyStore.storageService,
    'episode_completion_threshold': StorageKeyStore.storageService,
    'playback_completion_migration_generation': StorageKeyStore.storageService,
    'resume_ghost_purge_generation': StorageKeyStore.storageService,
    'android_video_renderer_mode': StorageKeyStore.storageService,
    'android_video_renderer_gpu_migration_v1': StorageKeyStore.storageService,
    'tvos_force_software_decode': StorageKeyStore.storageService,
    'player_audio_passthrough': StorageKeyStore.storageService,
    'player_apple_multichannel_audio': StorageKeyStore.storageService,
    'tvos_force_stereo_audio_v1': StorageKeyStore.storageService,
    'tvos_legacy_audio_output_v1': StorageKeyStore.storageService,
    'ui_sounds': StorageKeyStore.storageService,
    'ui_haptics': StorageKeyStore.storageService,
    'subtitle_auto_sync_enabled': StorageKeyStore.storageService,
    'player_default_subtitle_language': StorageKeyStore.storageService,
    'player_default_audio_language': StorageKeyStore.storageService,
    'skip_segments_enabled': StorageKeyStore.storageService,
    'skip_segment_provider': StorageKeyStore.storageService,
    'iptv_playlists': StorageKeyStore.storageService,
    'iptv_default_playlist': StorageKeyStore.storageService,
    'iptv_defaults_initialized': StorageKeyStore.storageService,
    'iptv_last_live_channel': StorageKeyStore.storageService,
    'pikpak_enabled': StorageKeyStore.storageService,
    'pikpak_email': StorageKeyStore.cloudSecretPrefs,
    'pikpak_password': StorageKeyStore.cloudSecretPrefs,
    'pikpak_access_token': StorageKeyStore.storageService,
    'pikpak_refresh_token': StorageKeyStore.storageService,
    'pikpak_device_id': StorageKeyStore.storageService,
    'pikpak_captcha_token': StorageKeyStore.storageService,
    'pikpak_user_id': StorageKeyStore.storageService,
    'pikpak_show_videos_only': StorageKeyStore.storageService,
    'pikpak_ignore_small_videos': StorageKeyStore.storageService,
    'pikpak_restricted_folder_id': StorageKeyStore.storageService,
    'pikpak_restricted_folder_name': StorageKeyStore.storageService,
    'pikpak_torrents_folder_id': StorageKeyStore.storageService,
    'pikpak_tv_folder_id': StorageKeyStore.storageService,
    'webdav_enabled': StorageKeyStore.storageService,
    'webdav_hidden_from_nav': StorageKeyStore.storageService,
    'webdav_base_url': StorageKeyStore.storageService,
    'webdav_username': StorageKeyStore.storageService,
    'webdav_password': StorageKeyStore.storageService,
    'webdav_show_videos_only': StorageKeyStore.storageService,
    'webdav_servers_v1': StorageKeyStore.storageService,
    'webdav_selected_server_id_v1': StorageKeyStore.storageService,
    'tvmaze_series_mappings': StorageKeyStore.storageService,
    'playlist_poster_overrides_v1': StorageKeyStore.storageService,
    'debrify_tv_favorite_channels_v1': StorageKeyStore.storageService,
    'stremio_tv_rotation_minutes': StorageKeyStore.storageService,
    'stremio_tv_series_rotation_minutes': StorageKeyStore.storageService,
    'stremio_tv_auto_refresh': StorageKeyStore.storageService,
    'stremio_tv_favorite_channels_v1': StorageKeyStore.storageService,
    'stremio_tv_preferred_quality': StorageKeyStore.storageService,
    'stremio_tv_debrid_provider': StorageKeyStore.storageService,
    'stremio_tv_max_start_percent': StorageKeyStore.storageService,
    'stremio_tv_random_episodes': StorageKeyStore.storageService,
    'stremio_tv_local_catalogs_v1': StorageKeyStore.storageService,
    'stremio_tv_catalog_repo_urls_v1': StorageKeyStore.storageService,
    'stremio_tv_hide_now_playing': StorageKeyStore.storageService,
    'stremio_tv_torrents_first': StorageKeyStore.storageService,
    'user_playlist_v1': StorageKeyStore.storageService,
    'playlist_view_modes_v1': StorageKeyStore.storageService,
    'playlist_favorites_v1': StorageKeyStore.storageService,
    'my_watchlist_v1': StorageKeyStore.storageService,
    'initial_setup_complete_v1': StorageKeyStore.storageService,
    'torrent_search_history_v1': StorageKeyStore.storageService,
    'torrent_search_history_enabled': StorageKeyStore.storageService,
    'default_filter_qualities_v1': StorageKeyStore.storageService,
    'default_filter_rip_sources_v1': StorageKeyStore.storageService,
    'default_filter_languages_v1': StorageKeyStore.storageService,
    'default_filter_sizes_v1': StorageKeyStore.storageService,
    'default_filter_dynamic_ranges_v1': StorageKeyStore.storageService,
    'quick_play_honors_filters_v1': StorageKeyStore.storageService,
    'default_torrent_provider_v1': StorageKeyStore.storageService,
    'indexer_manager_configs_v1': StorageKeyStore.storageService,
    'quick_play_vr_mode': StorageKeyStore.storageService,
    'quick_play_vr_default_screen_type': StorageKeyStore.storageService,
    'quick_play_vr_default_stereo_mode': StorageKeyStore.storageService,
    'quick_play_vr_auto_detect_format': StorageKeyStore.storageService,
    'quick_play_vr_show_dialog': StorageKeyStore.storageService,
    'quick_play_try_multiple_torrents': StorageKeyStore.storageService,
    'quick_play_max_retries': StorageKeyStore.storageService,
    'quick_play_movie_rules_v2': StorageKeyStore.storageService,
    'quick_play_series_rules_v2': StorageKeyStore.storageService,
    'play_button_mode': StorageKeyStore.storageService,
    'auto_bind_series_packs_on_play': StorageKeyStore.storageService,
    'series_auto_pin_on_play': StorageKeyStore.storageService,
    'trakt_access_token': StorageKeyStore.storageService,
    'trakt_refresh_token': StorageKeyStore.storageService,
    'trakt_username': StorageKeyStore.storageService,
    'trakt_token_expiry': StorageKeyStore.storageService,
    'simkl_access_token': StorageKeyStore.storageService,
    'simkl_username': StorageKeyStore.storageService,
    'mdblist_api_key': StorageKeyStore.storageService,
    'mdblist_username': StorageKeyStore.storageService,
    'remote_control_enabled': StorageKeyStore.storageService,
    'remote_intro_shown': StorageKeyStore.storageService,
    'remote_tv_device_name': StorageKeyStore.storageService,
    'remote_last_device': StorageKeyStore.storageService,
    'tvos_keyboard_default_generation': StorageKeyStore.storageService,
    'tv_low_res_render': StorageKeyStore.storageService,
    'tv_hero_artwork_quality': StorageKeyStore.storageService,
    'phone_nav_style': StorageKeyStore.storageService,
    'phone_nav_bar_indices': StorageKeyStore.storageService,
    'tv_home_style': StorageKeyStore.homePrefs,
    'debrify_tv_style': StorageKeyStore.storageService,
    'detail_page_style': StorageKeyStore.storageService,
    'detail_theme': StorageKeyStore.storageService,
    'app_theme': StorageKeyStore.storageService,
    'theme_overrides': StorageKeyStore.storageService,
    'parents_guide_style': StorageKeyStore.storageService,
    'iptv_style': StorageKeyStore.storageService,
    'iptv_channel_preview_enabled': StorageKeyStore.storageService,
    'player_dock_style': StorageKeyStore.storageService,
    'player_dock_palette': StorageKeyStore.storageService,
    'player_dock_size': StorageKeyStore.storageService,
    'iptv_player_guide_style': StorageKeyStore.storageService,
    'play_loader_style': StorageKeyStore.storageService,
    'tv_player_controls_style': StorageKeyStore.storageService,
    'debrify_tv_player_style': StorageKeyStore.storageService,
    'discover_layout': StorageKeyStore.storageService,
    'discover_default_source': StorageKeyStore.storageService,
    'discover_last_source': StorageKeyStore.storageService,
    'launch_animation': StorageKeyStore.storageService,
    'launch_ident_palette': StorageKeyStore.storageService,
    'text_brightness': StorageKeyStore.storageService,
    'tv_sidebar_style': StorageKeyStore.storageService,
    'desktop_sidebar_style': StorageKeyStore.storageService,
    'sidebar_configuration_v1': StorageKeyStore.storageService,
    'mdblist_saved_clones': StorageKeyStore.storageService,
    'mdblist_sync_checkpoint_v1': StorageKeyStore.storageService,
    'download_tree_uri_v1': StorageKeyStore.storageService,
    'download_tree_display_name_v1': StorageKeyStore.storageService,
    'download_dir_path_v1': StorageKeyStore.storageService,
    'episode_trakt_progress_v2': StorageKeyStore.storageService,
    'episode_simkl_progress_v1': StorageKeyStore.storageService,
    'episode_mdblist_progress_v1': StorageKeyStore.storageService,
    'iptv_track_continue_watching': StorageKeyStore.storageService,
    'quick_play_search_timeout': StorageKeyStore.storageService,
    'stremio_sources_timeout': StorageKeyStore.storageService,
    'iptv_series_audio_lang': StorageKeyStore.storageService,
    'startup_iptv_mode': StorageKeyStore.storageService,
    'startup_iptv_channel': StorageKeyStore.storageService,
    'stremio_tv_disabled_channel_filters_v1': StorageKeyStore.storageService,
    'catalog_search_disabled_addons_v1': StorageKeyStore.storageService,
    'home_disabled_sections_v1': StorageKeyStore.homePrefs,
    'home_extra_rows_v1': StorageKeyStore.homePrefs,
    'home_row_order_v1': StorageKeyStore.homePrefs,
    'home_hero_source_v1': StorageKeyStore.homePrefs,
    'home_hero_trailer_enabled': StorageKeyStore.homePrefs,
    'home_hero_trailer_audio_enabled': StorageKeyStore.homePrefs,
    'home_hero_trailer_volume': StorageKeyStore.homePrefs,
    'real_debrid_api_key': StorageKeyStore.cloudSecretPrefs,
  };

  static Set<String> keysFor(StorageKeyStore store) => {
    for (final e in byKey.entries)
      if (e.value == store) e.key,
  };
}
