import 'package:flutter/material.dart';

import 'settings_page_registry.dart';
import 'settings_page_spec.dart';
import 'settings_search_leaves.dart';
import 'widgets/settings_widgets.dart';

const kCatHome = 'Home & Display';
const kCatAppearance = 'Appearance';
const kCatPlayback = 'Playback';
const kCatSearch = 'Search';
const kCatDiscover = 'Discover';
const kCatLiveTv = 'Live TV & DVR';
const kCatDevices = 'Devices';
const kCatProfiles = 'Profiles';
const kCatData = 'Data & Backup';
const kCatAbout = 'About';
const kCatDanger = 'Danger Zone';
const kCatAddons = 'Addons';
const kCatStremioTv = 'Stremio TV';

const kGroupPresets = 'Presets';
const kGroupTheme = 'Theme';
const kGroupLayouts = 'Screen layouts';
const kGroupDisplay = 'Display';
const kGroupPlayer = 'Player';
const kGroupDownloads = 'Downloads';
const kGroupMaintenance = 'Maintenance';
const kGroupBackup = 'Backup & Restore';
const kGroupDiagnostics = 'Diagnostics';
const kGroupUpdates = 'Updates';
const kGroupCommunity = 'Community & Support';

/// Production settings catalog. Adding a page is one [SettingsPageSpec]
/// in this list; phone, desktop, TV and search all iterate it.
List<SettingsPageSpec> buildSettingsPages(SettingsPageBindings b) {
  final leaves = settingsLeavesByPage(b);

  SettingsPageSpec page({
    required String id,
    required SettingsRowContent row,
    required String category,
    Future<void> Function()? opener,
    List<String> keywords = const [],
    bool phone = true,
    bool desktop = true,
    bool tv = true,
    bool search = true,
    int phoneOrder = 100,
    int desktopOrder = 100,
    int tvOrder = 100,
    String? phoneGroup,
    String? desktopGroup,
    String? tvGroup,
    SettingsRowKind kind = SettingsRowKind.tile,
    SettingsRowKind? phoneKind,
    SettingsRowKind? desktopKind,
    SettingsRowKind? tvKind,
    bool destructive = false,
    bool Function()? visible,
    bool Function(SettingsLayoutSurface surface)? visibleOn,
    bool Function()? searchVisible,
    String Function()? titleOf,
    String Function()? subtitleOf,
    Widget? Function()? trailingOf,
    String? tag,
    bool Function()? toggleValue,
    ValueChanged<bool>? onToggle,
    String? leafPageName,
  }) {
    return SettingsPageSpec(
      id: id,
      row: row,
      category: category,
      opener: opener,
      keywords: keywords,
      leaves: leaves[id] ?? const [],
      phone: phone,
      desktop: desktop,
      tv: tv,
      search: search,
      phoneOrder: phoneOrder,
      desktopOrder: desktopOrder,
      tvOrder: tvOrder,
      phoneGroup: phoneGroup,
      desktopGroup: desktopGroup,
      tvGroup: tvGroup,
      kind: kind,
      phoneKind: phoneKind,
      desktopKind: desktopKind,
      tvKind: tvKind,
      destructive: destructive,
      visible: visible,
      visibleOn: visibleOn,
      searchVisible: searchVisible,
      titleOf: titleOf,
      subtitleOf: subtitleOf,
      trailingOf: trailingOf,
      tag: tag,
      toggleValue: toggleValue,
      onToggle: onToggle,
      leafPageName: leafPageName,
    );
  }

  return [
    // --- Home & Display ---
    page(
      id: 'homePage',
      row: SettingsRows.homePage,
      category: kCatHome,
      opener: b.openHomePage,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const [
        'home page',
        'default view',
        'startup',
        'landing',
        'tab',
      ],
    ),
    page(
      id: 'tvKeyboard',
      row: SettingsRows.tvKeyboard,
      category: kCatHome,
      phone: true,
      desktop: false,
      tv: true,
      phoneOrder: 20,
      tvOrder: 20,
      kind: SettingsRowKind.toggle,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? true : b.isAndroidTv,
      toggleValue: () => b.tvKeyboardEnabled,
      onToggle: b.onToggleTvKeyboard,
      keywords: const [
        'on-screen keyboard',
        'remote',
        'text input',
        'ime',
        'typing',
        'voice',
        'mic',
        'microphone',
        'dictation',
        'speak',
      ],
    ),
    page(
      id: 'navigationStyle',
      row: SettingsRows.navigationStyle,
      category: kCatHome,
      opener: b.openNavigation,
      // Phone lists this under Appearance / Screen layouts; desktop under
      // Home & Display; TV never shows it (sidebar navigation).
      phone: false,
      desktop: true,
      tv: false,
      desktopOrder: 20,
      visible: () => !b.isTelevision,
      keywords: const [
        'navigation',
        'nav',
        'bottom bar',
        'tabs',
        'floating',
        'classic',
        'menu',
        'display',
        'home & display',
      ],
    ),
    page(
      id: 'desktopSidebarStyleHome',
      row: SettingsRows.desktopSidebarStyle,
      category: kCatHome,
      opener: b.openDesktopSidebarStyle,
      phone: false,
      desktop: true,
      tv: false,
      search: false,
      desktopOrder: 30,
      subtitleOf: () => b.desktopSidebarStyleLabel,
    ),

    // --- Appearance ---
    page(
      id: 'looks',
      row: SettingsRows.looks,
      category: kCatAppearance,
      opener: b.openLooks,
      phoneOrder: 10,
      desktopOrder: 0,
      tvOrder: 0,
      phoneGroup: kGroupPresets,
      desktopKind: SettingsRowKind.lookHero,
      tvKind: SettingsRowKind.lookHero,
      subtitleOf: () => b.looksLabel,
      keywords: [
        'app',
        'theme',
        'app theme',
        'whole app',
        'colour',
        'color',
        'palette',
        'look',
        'style',
        'skin',
        'dark',
        'light',
        'legacy',
        'classic',
        'experimental',
        ...b.extraLooksKeywords(),
      ],
    ),
    // Withheld rows: Theme Lab is a preview TOOL (changes nothing). App
    // Theme write-through-mirrors into detail_theme, so two rows set the
    // same thing. Wiring stays so restoring a row is a flag flip — the
    // same withheld-not-deleted pattern kDetailThemesShipped uses.
    page(
      id: 'themeLab',
      row: SettingsRows.themeLab,
      category: kCatAppearance,
      opener: b.openThemeLab,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'appTheme',
      row: SettingsRows.appTheme,
      category: kCatAppearance,
      opener: b.openAppTheme,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'detailTheme',
      row: SettingsRows.detailTheme,
      category: kCatAppearance,
      opener: b.openDetailTheme,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
      subtitleOf: () => b.detailThemeLabel,
    ),
    page(
      id: 'sidebarCustomization',
      row: SettingsRows.tvSidebarStyle,
      category: kCatAppearance,
      opener: b.openSidebarCustomization,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
      leafPageName: 'Sidebar',
    ),
    page(
      id: 'themeTokens',
      row: SettingsRows.themeTokens,
      category: kCatAppearance,
      opener: b.openThemeTokens,
      phoneOrder: 20,
      desktopOrder: 10,
      tvOrder: 10,
      phoneGroup: kGroupPresets,
      desktopGroup: kGroupPresets,
      tvGroup: kGroupPresets,
      leafPageName: 'Advanced',
      subtitleOf: () => b.themeTokensLabel,
      keywords: const [
        'advanced',
        'token',
        'colour',
        'color',
        'accent',
        'background',
        'font',
        'corner',
        'motion',
      ],
    ),
    page(
      id: 'textBrightness',
      row: SettingsRows.textBrightness,
      category: kCatAppearance,
      opener: b.openTextBrightness,
      phoneOrder: 30,
      desktopOrder: 20,
      tvOrder: 20,
      phoneGroup: kGroupTheme,
      desktopGroup: kGroupTheme,
      tvGroup: kGroupTheme,
      subtitleOf: () => b.textBrightnessLabel,
      keywords: [
        'text',
        'font',
        'color',
        'colour',
        'grey',
        'gray',
        'white',
        'dim',
        'dimmer',
        'brightness',
        'bright',
        'oled',
        'amoled',
        'contrast',
        'glare',
        'display',
        ...b.extraTextBrightnessKeywords(),
      ],
    ),
    page(
      id: 'launchAnimation',
      row: SettingsRows.launchAnimation,
      category: kCatAppearance,
      opener: b.openLaunchAnimation,
      phoneOrder: 40,
      desktopOrder: 30,
      tvOrder: 30,
      phoneGroup: kGroupTheme,
      desktopGroup: kGroupTheme,
      tvGroup: kGroupTheme,
      subtitleOf: () => b.launchAnimationLabel,
      keywords: [
        'launch',
        'splash',
        'intro',
        'animation',
        'boot',
        'start',
        'startup',
        'logo',
        'ident',
        'opening',
        'neon',
        'chrome',
        'marquee',
        'prism',
        'monogram',
        'match app theme',
        'ident colour',
        'ident color',
        ...b.extraLaunchAnimationKeywords(),
      ],
    ),
    page(
      id: 'tvHomeStyle',
      row: SettingsRows.tvHomeStyle,
      category: kCatAppearance,
      opener: b.openTvHomeStyle,
      phone: false,
      desktop: false,
      tv: true,
      search: true,
      tvOrder: 40,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.tvHomeStyleLabel,
      keywords: [
        'home',
        'layout',
        'home screen',
        'canvas',
        'spotlight',
        'shelf',
        'classic',
        'rows',
        'redesign',
        'view',
        'display',
        'home & display',
        ...b.extraTvHomeStyleKeywords(),
      ],
    ),
    page(
      id: 'discoverLayout',
      row: SettingsRows.discoverLayout,
      category: kCatAppearance,
      opener: b.openDiscoverLayout,
      phone: false,
      desktop: false,
      tv: true,
      search: true,
      tvOrder: 50,
      tvGroup: kGroupLayouts,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.discoverLayoutLabel,
      keywords: [
        'discover',
        'layout',
        'stage',
        'grid',
        'browse',
        'shelf',
        'catalog',
        'view',
        'posters',
        'display',
        'home & display',
        ...b.extraDiscoverLayoutKeywords(),
      ],
    ),
    page(
      id: 'detailPageStyle',
      row: SettingsRows.detailPageStyle,
      category: kCatAppearance,
      opener: b.openDetailPageStyle,
      phoneOrder: 50,
      desktopOrder: 40,
      tvOrder: 60,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.detailPageStyleLabel,
      keywords: [
        'details',
        'detail',
        'page',
        'layout',
        'style',
        'theme',
        'look',
        'movie',
        'series',
        'show',
        'episodes',
        'episode list',
        'marquee',
        'dossier',
        'broadsheet',
        'stage',
        'filmstrip',
        'console',
        'classic',
        ...b.extraDetailPageKeywords(),
      ],
    ),
    page(
      id: 'tvSidebarStyle',
      row: SettingsRows.tvSidebarStyle,
      category: kCatAppearance,
      opener: b.openTvSidebarStyle,
      phone: false,
      desktop: false,
      tv: true,
      search: true,
      tvOrder: 70,
      tvGroup: kGroupLayouts,
      searchVisible: () => b.isAndroidTv,
      leafPageName: 'Sidebar',
      subtitleOf: () => b.tvSidebarStyleLabel,
      keywords: [
        'sidebar',
        'nav',
        'navigation',
        'rail',
        'menu',
        'ghost',
        'island',
        'marquee',
        'badge',
        'dock',
        'display',
        'home & display',
        'order and names',
        'rename sidebar',
        ...b.extraTvSidebarKeywords(),
      ],
    ),
    page(
      id: 'iptvAppearance',
      row: SettingsRows.iptvAppearance,
      category: kCatAppearance,
      opener: b.openIptvStyle,
      phoneOrder: 60,
      desktopOrder: 50,
      tvOrder: 80,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      visibleOn: (s) =>
          s == SettingsLayoutSurface.tv ? true : b.iptvAppearanceSearchable,
      searchVisible: () => b.iptvAppearanceSearchable,
      subtitleOf: () => b.iptvStyleLabel,
      keywords: [
        'iptv',
        'style',
        'theme',
        'look',
        'skin',
        'appearance',
        'command center',
        'first edition',
        'master control',
        'cockpit',
        'premium',
        'live tv',
        'dvr',
        'live tv & dvr',
        ...b.extraIptvStyleKeywords(),
      ],
    ),
    page(
      id: 'debrifyTvAppearance',
      row: SettingsRows.debrifyTvAppearance,
      category: kCatAppearance,
      opener: b.openDebrifyTvStyle,
      phoneOrder: 70,
      desktopOrder: 60,
      tvOrder: 90,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.debrifyTvStyleLabel,
      keywords: [
        'debrify tv',
        'channels',
        'channel grid',
        'rail',
        'stage',
        'spotlight',
        'style',
        'layout',
        'look',
        'appearance',
        ...b.extraDebrifyTvStyleKeywords(),
      ],
    ),
    page(
      id: 'playerGuideStyle',
      row: SettingsRows.playerGuideStyle,
      category: kCatAppearance,
      opener: b.openPlayerGuideStyle,
      phoneOrder: 80,
      desktopOrder: 70,
      tvOrder: 100,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.playerGuideStyleLabel,
      keywords: [
        'iptv',
        'player',
        'guide',
        'zap',
        'banner',
        'style',
        'theme',
        'look',
        'skin',
        'cinema glass',
        'midnight edition',
        'master control',
        'classic',
        'live tv',
        'dvr',
        'live tv & dvr',
        ...b.extraPlayerGuideKeywords(),
      ],
    ),
    page(
      id: 'playLoaderStyle',
      row: SettingsRows.playLoaderStyle,
      category: kCatAppearance,
      opener: b.openPlayLoaderStyle,
      phoneOrder: 90,
      desktopOrder: 80,
      tvOrder: 110,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.playLoaderStyleLabel,
      keywords: [
        'play',
        'loading',
        'loader',
        'spinner',
        'searching',
        'resolving',
        'progress',
        'marquee',
        'backdrop',
        'logo',
        'stages',
        'pipeline',
        ...b.extraPlayLoaderKeywords(),
      ],
    ),
    page(
      id: 'playerDock',
      row: SettingsRows.playerDock,
      category: kCatAppearance,
      opener: b.openPlayerDock,
      tv: false,
      phoneOrder: 100,
      desktopOrder: 90,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      visible: () => !b.isTelevision,
      subtitleOf: () => b.playerDockLabel,
      keywords: [
        'player',
        'controls',
        'dock',
        'buttons',
        'seekbar',
        'scrubber',
        'size',
        'colour',
        'color',
        'palette',
        'style',
        'look',
        'big',
        'small',
        'layout',
        'accent',
        ...b.extraPlayerDockKeywords(),
      ],
    ),
    page(
      id: 'parentsGuideStyle',
      row: SettingsRows.parentsGuideStyle,
      category: kCatAppearance,
      opener: b.openParentsGuideStyle,
      phoneOrder: 110,
      desktopOrder: 100,
      tvOrder: 120,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      subtitleOf: () => b.parentsGuideStyleLabel,
      keywords: [
        'parents',
        'parental',
        'guide',
        'advisory',
        'content rating',
        'severity',
        'compass',
        'classic',
        'family',
        ...b.extraParentsGuideKeywords(),
      ],
    ),
    page(
      id: 'profileAppearance',
      row: SettingsRows.profileAppearance,
      category: kCatAppearance,
      opener: b.openProfileAppearance,
      phoneOrder: 120,
      desktopOrder: 110,
      tvOrder: 130,
      phoneGroup: kGroupLayouts,
      desktopGroup: kGroupLayouts,
      tvGroup: kGroupLayouts,
      leafPageName: 'Profile Picker',
      subtitleOf: () => b.profileAppearanceLabel,
      keywords: [
        'profile',
        'picker',
        'who is watching',
        'who\'s watching',
        'marquee',
        'theater',
        'portrait wall',
        'top shelf',
        'personalized top shelf',
        'apple tv',
        ...b.extraProfileAppearanceKeywords(),
      ],
    ),
    page(
      id: 'navigationStyleAppearance',
      row: SettingsRows.navigationStyle,
      category: kCatAppearance,
      opener: b.openNavigation,
      desktop: false,
      tv: false,
      search: false,
      phoneOrder: 130,
      phoneGroup: kGroupLayouts,
      visible: () => !b.isTelevision,
      subtitleOf: () => b.phoneNavStyleLabel,
    ),
    page(
      id: 'desktopSidebarStyle',
      row: SettingsRows.desktopSidebarStyle,
      category: kCatAppearance,
      opener: b.openDesktopSidebarStyle,
      desktop: false,
      tv: false,
      phoneOrder: 140,
      phoneGroup: kGroupLayouts,
      visible: () => !b.isAndroidTv && !b.isTelevision,
      subtitleOf: () => b.desktopSidebarStyleLabel,
      keywords: [
        'sidebar',
        'nav',
        'navigation',
        'rail',
        'menu',
        'pill',
        'desktop',
        'tablet',
        'ipad',
        'display',
        'home & display',
        'order and names',
        'rename sidebar',
        ...b.extraDesktopSidebarKeywords(),
      ],
    ),
    page(
      id: 'tvScreenSize',
      row: SettingsRows.tvScreenSize,
      category: kCatAppearance,
      opener: b.openTvScreenSize,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 140,
      tvGroup: kGroupDisplay,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvUiScaleLabel,
      keywords: [
        'zoom',
        'zoomed in',
        'scale',
        'ui size',
        'text size',
        'font size',
        'bigger',
        'smaller',
        'density',
        'dpi',
        'resolution',
        'compact',
        'fit more',
        'display',
        'home & display',
        ...b.extraTvScreenSizeKeywords(),
      ],
    ),
    page(
      id: 'tvRenderQuality',
      row: SettingsRows.tvRenderQuality,
      category: kCatAppearance,
      opener: b.openTvRenderQuality,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 150,
      tvGroup: kGroupDisplay,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvRenderQualityLabel,
      keywords: [
        'stutter',
        'stuttering',
        'lag',
        'laggy',
        'jank',
        'janky',
        'choppy',
        'slow',
        'smooth',
        'smoothness',
        'performance',
        'fps',
        'frame rate',
        'speed',
        'scrolling',
        'resolution',
        'render',
        'rendering',
        '720p',
        '1080p',
        'sharp',
        'sharpness',
        'blurry',
        'soft',
        'quality',
        'gpu',
        'graphics',
        'display',
        'home & display',
        ...b.extraTvRenderQualityKeywords(),
      ],
    ),
    page(
      id: 'tvHeroArtworkQuality',
      row: SettingsRows.tvHeroArtworkQuality,
      category: kCatAppearance,
      opener: b.openTvHeroArtworkQuality,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 160,
      tvGroup: kGroupDisplay,
      searchVisible: () => b.isTelevision,
      subtitleOf: () => b.tvHeroArtworkQualityLabel,
      keywords: [
        'hero',
        'artwork',
        'image',
        'picture',
        'poster',
        'backdrop',
        'quality',
        'resolution',
        '1080p',
        'full hd',
        'sharp',
        'memory',
        'performance',
        'home',
        'tv',
        ...b.extraTvHeroArtworkKeywords(),
      ],
    ),
    page(
      id: 'tvPlayerControls',
      row: SettingsRows.tvPlayerControls,
      category: kCatAppearance,
      opener: b.openTvPlayerControlsStyle,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 170,
      tvGroup: kGroupPlayer,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? b.isAndroidTv : false,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvPlayerControlsStyleLabel,
      keywords: [
        'player',
        'controls',
        'dock',
        'buttons',
        'seekbar',
        'scrubber',
        'transport',
        'ott',
        'legacy',
        'cinema',
        'style',
        'look',
        'skin',
        ...b.extraTvPlayerControlsKeywords(),
      ],
    ),
    page(
      id: 'debrifyTvPlayer',
      row: SettingsRows.debrifyTvPlayer,
      category: kCatAppearance,
      opener: b.openDebrifyTvPlayerStyle,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 180,
      tvGroup: kGroupPlayer,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? b.isAndroidTv : false,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.debrifyTvPlayerStyleLabel,
      keywords: [
        'debrify tv',
        'magic tv',
        'channel',
        'player',
        'network',
        'cinema',
        'guide',
        'spotlight',
        'prestige',
        'badge',
        'quality',
        'style',
        'look',
        'skin',
        ...b.extraDebrifyTvPlayerKeywords(),
      ],
    ),

    // --- Playback ---
    page(
      id: 'player',
      row: SettingsRows.player,
      category: kCatPlayback,
      opener: b.openExternalPlayer,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: [
        'external player',
        'video player',
        if (b.isAndroid) ...['system app chooser', 'vlc', 'mx player'],
        'subtitle',
        'subtitles',
        'audio track',
        'skip intro',
        'skip credits',
        'outro',
        'auto provider',
        'skipdb',
        'introdb',
        'theintrodb',
        'watch history',
        'watched',
        'completion',
        'threshold',
        'movie',
        'episode',
        ...b.extraPlayerKeywords(),
      ],
    ),

    // --- Search ---
    page(
      id: 'searchSettings',
      row: SettingsRows.searchSettings,
      category: kCatSearch,
      opener: b.openTorrentSettings,
      leafPageName: 'Engines',
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const ['engines', 'sorting', 'torrent', 'sources'],
    ),
    page(
      id: 'filterSettings',
      row: SettingsRows.filterSettings,
      category: kCatSearch,
      opener: b.openFilterSettings,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      keywords: const [
        'quality',
        'resolution',
        '1080p',
        '4k',
        '2160p',
        'hdr',
        'language',
        'codec',
        'hevc',
        'sdr',
        'dolby vision',
        'dynamic range',
      ],
    ),
    page(
      id: 'providerSettings',
      row: SettingsRows.providerSettings,
      category: kCatSearch,
      opener: b.openProviderSettings,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      keywords: const [
        'default provider',
        'add torrent',
        'debrid',
        'ask every time',
        'show provider selection dialog',
        'torbox',
        'real-debrid',
        'premiumize',
        'alldebrid',
        'pikpak',
      ],
    ),
    page(
      id: 'quickPlay',
      row: SettingsRows.quickPlay,
      category: kCatSearch,
      opener: b.openQuickPlay,
      phoneOrder: 40,
      desktopOrder: 40,
      tvOrder: 40,
      keywords: const ['instant', 'auto play', 'one tap'],
    ),

    // --- Discover ---
    page(
      id: 'discoverDefault',
      row: SettingsRows.discoverDefault,
      category: kCatDiscover,
      opener: b.openDiscover,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const [
        'remember last',
        'default source',
        'continue watching',
        'trakt',
        'simkl',
        'stremio addon',
        'movie tag',
        'series tag',
        'ratings',
        'poster titles',
        'hide titles',
      ],
    ),

    // --- Live TV & DVR ---
    page(
      id: 'debrifyTv',
      row: SettingsRows.debrifyTv,
      category: kCatLiveTv,
      opener: b.openDebrifyTv,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const ['channels', 'limits', 'playback', 'android tv'],
    ),
    page(
      id: 'recordings',
      row: SettingsRows.recordings,
      category: kCatLiveTv,
      opener: b.openRecordings,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      keywords: const [
        'record',
        'recording',
        'recordings',
        'dvr',
        'schedule',
        'scheduled',
        'timer',
        'rec',
        'library',
        'capture',
        'iptv',
        'live tv',
      ],
    ),
    page(
      id: 'iptvPlaylists',
      row: SettingsRows.iptvPlaylists,
      category: kCatLiveTv,
      opener: b.openIptv,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      keywords: const ['m3u', 'xtream', 'channels', 'epg', 'live tv'],
    ),

    // --- Devices ---
    page(
      id: 'remote',
      row: SettingsRows.remote,
      category: kCatDevices,
      opener: b.openRemote,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const ['cast', 'handoff', 'phone', 'receive', 'send', 'setup'],
    ),

    // --- Profiles ---
    page(
      id: 'switchProfile',
      row: SettingsRows.switchProfile,
      category: kCatProfiles,
      opener: b.openSwitchProfile,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'profile',
        'profiles',
        'switch',
        'switch to this profile',
        'who is watching',
        'avatar',
        'pin',
        'kids',
        'account',
        'startup',
        'always ask',
        'household',
        'backup',
        'restore',
        'send to tv',
        'transfer',
        'delete profile',
        'disable profile',
      ],
    ),
    page(
      id: 'addProfile',
      row: SettingsRows.addProfile,
      category: kCatProfiles,
      opener: b.openAddProfile,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'create profile',
        'new profile',
        'add user',
        'kid',
        'member',
        'admin',
        'start from my settings',
        'copy appearance and playback defaults',
        'search by title',
        'keyword search',
        'debrify tv',
        'stremio tv',
        'live tv',
        'youtube',
        'download and record',
        'remote',
        'manage own sources',
        'cloud files',
      ],
    ),
    page(
      id: 'editProfile',
      row: SettingsRows.editProfile,
      category: kCatProfiles,
      opener: b.openEditProfile,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'rename',
        'avatar',
        'pin',
        'access',
        'permissions',
        'edit user',
        'save name and avatar',
        'choose image',
        'gif',
        'set pin',
        'change pin',
        'remove pin',
        'pin protection',
        'lock when the app resumes',
        'auto-lock',
        'after 5 minutes',
        'after 15 minutes',
        'after 30 minutes',
        'after 1 hour',
        'copy appearance and playback defaults',
        'role',
        'admin',
        'member',
        'kid',
        'pages and abilities',
        'keyword search',
        'live tv',
        'youtube',
        'download and record',
        'manage own sources',
        'cloud files',
        'torrent engines',
        'debrid and cloud',
        'addons',
        'trackers and lists',
        'live tv and indexers',
        'transfer ownership',
        'diagnostics',
        're-run the questions',
        'full editor',
      ],
    ),

    // --- Data & Backup ---
    page(
      id: 'downloadLocation',
      row: SettingsRows.downloadLocation,
      category: kCatData,
      opener: b.openDownloadLocation,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      desktopGroup: kGroupDownloads,
      tvGroup: kGroupDownloads,
      visible: () => b.downloadLocationSupported,
      subtitleOf: () => b.downloadLocationSubtitle,
      keywords: const [
        'sd card',
        'folder',
        'external storage',
        'saf',
        'location',
        'path',
        'directory',
        'sd',
        'choose folder',
        'reset to default',
        'another drive',
      ],
    ),
    page(
      id: 'clearDownloads',
      row: SettingsRows.clearDownloads,
      category: kCatData,
      opener: b.clearDownloads,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      desktopGroup: kGroupMaintenance,
      tvGroup: kGroupMaintenance,
      keywords: const ['queue', 'history', 'clear', 'remove'],
    ),
    page(
      id: 'clearPlayback',
      row: SettingsRows.clearPlayback,
      category: kCatData,
      opener: b.clearPlayback,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      desktopGroup: kGroupMaintenance,
      tvGroup: kGroupMaintenance,
      keywords: const [
        'resume',
        'watch history',
        'reset progress',
        'continue watching',
      ],
    ),
    page(
      id: 'createBackup',
      row: SettingsRows.createBackup,
      category: kCatData,
      opener: b.createBackup,
      phoneOrder: 40,
      desktopOrder: 40,
      tvOrder: 40,
      desktopGroup: kGroupBackup,
      tvGroup: kGroupBackup,
      keywords: const [
        'export',
        'save',
        'addons',
        'search engines',
        'all profiles',
        'shared connections',
        'encrypted',
        'password',
        'passphrase',
        'minimum 8 characters',
        'recovery code',
      ],
    ),
    page(
      id: 'restoreBackup',
      row: SettingsRows.restoreBackup,
      category: kCatData,
      opener: b.restoreBackup,
      phoneOrder: 50,
      desktopOrder: 50,
      tvOrder: 50,
      desktopGroup: kGroupBackup,
      tvGroup: kGroupBackup,
      keywords: const [
        'import',
        'load',
        'encrypted',
        'password',
        'passphrase',
        'unlock backup',
        'admin pin',
        'confirm admin pin',
        'profiles',
        'connections',
      ],
    ),
    page(
      id: 'exportDiagnosticLogs',
      row: SettingsRows.exportDiagnosticLogs,
      category: kCatData,
      opener: b.exportDiagnosticLogs,
      phoneOrder: 60,
      desktopOrder: 60,
      tvOrder: 60,
      desktopGroup: kGroupDiagnostics,
      tvGroup: kGroupDiagnostics,
      visible: () => b.diagnosticExportVisible,
      keywords: const [
        'logs',
        'diagnostics',
        'debug',
        'crash',
        'support',
        'android tv',
        'last two hours',
      ],
    ),

    // --- About ---
    page(
      id: 'autoUpdate',
      row: SettingsRows.autoUpdate,
      category: kCatAbout,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      kind: SettingsRowKind.toggle,
      toggleValue: () => b.autoUpdateChecksEnabled,
      onToggle: b.onToggleAutoUpdateChecks,
      keywords: const ['notify', 'releases', 'startup'],
    ),
    page(
      id: 'checkUpdates',
      row: SettingsRows.checkUpdates,
      category: kCatAbout,
      opener: b.checkUpdates,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      subtitleOf: () => b.updateSubtitle,
      tag: 'New',
      trailingOf: () => b.checkingUpdates
          ? const SizedBox(
              width: 20,
              height: 20,
              child: CircularProgressIndicator(strokeWidth: 2.5),
            )
          : null,
      keywords: const ['version', 'upgrade', 'github', 'new build'],
    ),
    page(
      id: 'version',
      row: SettingsRows.version,
      category: kCatAbout,
      phoneOrder: 70,
      desktopOrder: 30,
      tvOrder: 30,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      kind: SettingsRowKind.info,
      search: false,
      subtitleOf: () => b.appVersion,
    ),
    page(
      id: 'supportDonation',
      row: SettingsRows.supportDebrify,
      category: kCatAbout,
      opener: b.openSupportDonation,
      phoneOrder: 30,
      desktopOrder: 40,
      tvOrder: 40,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      visible: () => b.showSupportDonation,
      titleOf: () => b.supportDonationLabel,
      subtitleOf: () => b.supportDonationSubtitle,
      keywords: const ['donate', 'tip', 'contribute', 'fund'],
    ),
    page(
      id: 'reddit',
      row: SettingsRows.reddit,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.reddit.url!),
      phoneOrder: 40,
      desktopOrder: 50,
      tvOrder: 50,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['community', 'subreddit'],
    ),
    page(
      id: 'discord',
      row: SettingsRows.discord,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.discord.url!),
      phoneOrder: 50,
      desktopOrder: 60,
      tvOrder: 60,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['community', 'chat', 'help'],
    ),
    page(
      id: 'github',
      row: SettingsRows.github,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.github.url!),
      phoneOrder: 60,
      desktopOrder: 70,
      tvOrder: 70,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['source code', 'contribute', 'issues'],
    ),

    // --- Danger Zone ---
    page(
      id: 'resetDebrify',
      row: SettingsRows.resetDebrify,
      category: kCatDanger,
      opener: b.resetApp,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      destructive: true,
      keywords: const ['wipe', 'factory reset', 'clear all', 'erase'],
    ),

    // --- Search-only destinations (not root rows) ---
    page(
      id: 'collections',
      row: SettingsRows.collections,
      category: kCatHome,
      opener: b.openCollections,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'collections',
        'collection',
        'nuvio',
        'xperience',
        'folders',
        'import json',
      ],
    ),
    page(
      id: 'addons',
      row: const SettingsRowContent(
        icon: Icons.extension_rounded,
        title: 'Addons',
        subtitle: 'Stremio addons and torrent search engines',
      ),
      category: kCatAddons,
      opener: b.openAddons,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'addon',
        'addons',
        'stremio',
        'manifest',
        'install',
        'catalog',
        'catalogs',
        'subtitles',
        'torrentio',
        'marketplace',
        'engine',
        'engines',
        'import',
        'yaml',
        'add engine',
        'import from file',
        'remove addon',
        'delete all addons',
        'view details',
        'resources',
        'id prefixes',
        'last checked',
      ],
    ),
    page(
      id: 'stremioTv',
      row: const SettingsRowContent(
        icon: Icons.smart_display_rounded,
        title: 'Stremio TV',
        subtitle: 'Rotation, quality, provider and playback for Stremio TV',
      ),
      category: kCatStremioTv,
      opener: b.openStremioTv,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'stremio tv',
        'channel',
        'channels',
        'rotation',
        'series rotation',
        'random',
        'episodes',
        'quality',
        'debrid provider',
        'torrents first',
        'auto-refresh',
        'now playing',
        'start position',
      ],
    ),
    page(
      id: 'iptvLists',
      row: const SettingsRowContent(
        icon: Icons.bookmark_rounded,
        title: 'IPTV lists',
        subtitle: 'Create and manage your channel lists',
      ),
      category: kCatLiveTv,
      opener: b.openIptv,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'list',
        'lists',
        'favorites',
        'favourites',
        'saved channels',
        'iptv',
        'collection',
      ],
    ),
    page(
      id: 'startupChannel',
      row: const SettingsRowContent(
        icon: Icons.live_tv_rounded,
        title: 'Startup channel',
        subtitle: 'Open straight into a live channel when the app starts',
      ),
      category: kCatLiveTv,
      opener: b.openIptv,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'startup',
        'start up',
        'boot',
        'launch',
        'auto play',
        'autoplay',
        'auto launch',
        'last watched',
        'on open',
        'iptv',
        'live tv',
      ],
    ),
    page(
      id: 'iptvContinueWatching',
      row: const SettingsRowContent(
        icon: Icons.history_toggle_off_rounded,
        title: 'IPTV continue watching',
        subtitle: 'Track the movies and series you start on IPTV',
      ),
      category: kCatLiveTv,
      opener: b.openIptv,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'continue watching',
        'continue',
        'resume',
        'history',
        'watch history',
        'track',
        'tracking',
        'shelf',
        'iptv',
        'vod',
        'movies',
        'series',
      ],
    ),

    // Leaf hosts for connection pages — not root rows (those stay
    // ConnectionInfo cards); search-false so the live conn() entry is
    // the one title users see, while in-page options still index.
    page(
      id: 'torbox',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'Torbox',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openTorbox,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'premiumize',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'Premiumize',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openPremiumize,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'realDebrid',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'Real Debrid',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openRealDebrid,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'allDebrid',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'AllDebrid',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openAllDebrid,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'pikpak',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'PikPak',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openPikPak,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'webDav',
      row: const SettingsRowContent(
        icon: Icons.cloud_rounded,
        title: 'WebDAV',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openWebDav,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'indexerManagers',
      row: const SettingsRowContent(
        icon: Icons.manage_search_rounded,
        title: 'Indexer Managers',
        subtitle: '',
      ),
      category: 'Connections',
      opener: b.openIndexerManagers,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'tracking',
      row: const SettingsRowContent(
        icon: Icons.sync_alt_rounded,
        title: 'Tracking',
        subtitle: '',
      ),
      category: 'Trackers',
      opener: b.openTracking,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'trakt',
      row: const SettingsRowContent(
        icon: Icons.sync_rounded,
        title: 'Trakt',
        subtitle: '',
      ),
      category: 'Trackers',
      opener: b.openTrakt,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'simkl',
      row: const SettingsRowContent(
        icon: Icons.sync_rounded,
        title: 'Simkl',
        subtitle: '',
      ),
      category: 'Trackers',
      opener: b.openSimkl,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
    ),
    page(
      id: 'mdblist',
      row: const SettingsRowContent(
        icon: Icons.list_alt_rounded,
        title: 'MDBList',
        subtitle: '',
      ),
      category: 'Trackers',
      opener: b.openMdblist,
      phone: false,
      desktop: false,
      tv: false,
      search: false,
      visible: () => b.mdblistEnabled,
    ),
  ];
}

SettingsPageRegistry productionSettingsRegistry(SettingsPageBindings b) =>
    SettingsPageRegistry(pages: buildSettingsPages(b));
