import 'settings_page_spec.dart';

/// In-page options, keyed by [SettingsPageSpec.id]. Moved verbatim from
/// `_leafSearchEntries` in settings_screen.dart; titles and keywords are
/// quirks (searchers type the in-page label, not the rail name).
Map<String, List<SettingsLeafSpec>> settingsLeavesByPage(
  SettingsPageBindings b,
) {
  SettingsLeafSpec leaf(
    String title,
    String subtitle,
    List<String> keywords, {
    Future<void> Function()? onTap,
    bool Function()? visible,
  }) => SettingsLeafSpec(
    title: title,
    subtitle: subtitle,
    keywords: keywords,
    onTap: onTap,
    visible: visible,
  );

  return {
    'torbox': [
      leaf(
        'Check Torbox cache during searches',
        'Verify a cached copy before enabling quick actions',
        const ['cache', 'cached', 'quick action', 'badge', 'instant'],
      ),
      leaf(
        'Post-Torrent Action',
        'What happens after adding a torrent to Torbox',
        const [
          'after adding',
          'post torrent',
          'none',
          'let me choose',
          'play video',
          'download to device',
          'open in torbox',
          'add to playlist',
          'add to channel',
          'debrify tv',
        ],
      ),
      leaf(
        'Hide Torbox from Navigation',
        'Hide the Torbox tab from the nav bar',
        const ['hide', 'navigation', 'nav', 'tab'],
      ),
      leaf('Enable Torbox', 'Turn the Torbox integration on or off', const [
        'enable',
        'disable',
        'turn off',
        'integration',
        'account',
      ]),
    ],
    'premiumize': [
      leaf(
        'Check Premiumize cache during searches',
        'Show a cached badge on Premiumize results',
        const ['cache', 'cached', 'badge', 'instant'],
      ),
      leaf(
        'Post-Torrent Action',
        'What happens after adding a torrent to Premiumize',
        const [
          'after adding',
          'post torrent',
          'none',
          'let me choose',
          'play video',
          'download to device',
          'open in premiumize',
          'add to channel',
          'debrify tv',
        ],
      ),
      leaf(
        'Hide Premiumize from Navigation',
        'Hide the Premiumize tab from the nav bar',
        const ['hide', 'navigation', 'nav', 'tab'],
      ),
      leaf(
        'Enable Premiumize',
        'Turn the Premiumize integration on or off',
        const ['enable', 'disable', 'turn off', 'integration', 'account'],
      ),
    ],
    'realDebrid': [
      leaf(
        'File Selection',
        'How files are picked when adding to Real-Debrid',
        const [
          'file selection',
          'smart',
          'largest',
          'video files',
          'all files',
        ],
      ),
      leaf(
        'Post-Torrent Action',
        'What happens after adding a torrent to Real-Debrid',
        const [
          'after adding',
          'post torrent',
          'none',
          'let me choose',
          'play video',
          'download to device',
          'open in real-debrid',
          'add to playlist',
          'add to channel',
          'debrify tv',
        ],
      ),
      leaf(
        'Skip blocked torrents',
        'Skip likely-blocked releases in Quick Play',
        const [
          'content filter',
          'bypass',
          'blocked',
          'web-dl',
          'webrip',
          'hdrip',
        ],
      ),
      leaf(
        'Hide Real Debrid from Navigation',
        'Hide the Real-Debrid tab from the nav bar',
        const ['hide', 'navigation', 'nav', 'tab'],
      ),
      leaf(
        'Enable Real Debrid',
        'Turn the Real-Debrid integration on or off',
        const ['enable', 'disable', 'turn off', 'integration', 'account'],
      ),
    ],
    'allDebrid': [
      leaf(
        'Post-Torrent Action',
        'What happens after adding a torrent to AllDebrid',
        const [
          'after adding',
          'post torrent',
          'none',
          'let me choose',
          'play video',
          'download to device',
        ],
      ),
      leaf(
        'Hide AllDebrid from Navigation',
        'Hide the AllDebrid tab from the nav bar',
        const ['hide', 'navigation', 'nav', 'tab'],
      ),
      leaf(
        'Enable AllDebrid',
        'Turn the AllDebrid integration on or off',
        const ['enable', 'disable', 'turn off', 'integration', 'account'],
      ),
    ],
    'pikpak': [
      leaf(
        'Show Only Video Files',
        'Filter PikPak folders to video files only',
        const ['video only', 'files', 'folders', 'filter'],
      ),
      leaf(
        'Ignore Videos Under 100MB',
        'Hide small video files in PikPak',
        const ['ignore small', '100mb', 'small videos', 'filter'],
      ),
      leaf(
        'Post-Torrent Action',
        'What happens after adding a torrent to PikPak',
        const [
          'after adding',
          'post torrent',
          'none',
          'let me choose',
          'play video',
          'download to device',
          'open in pikpak',
          'add to playlist',
          'add to channel',
          'debrify tv',
        ],
      ),
      leaf(
        'Restrict Access to Folder',
        'Limit PikPak access to a single folder',
        const [
          'restrict',
          'folder',
          'access',
          'security',
          'select folder',
          'change folder',
          'remove restriction',
        ],
      ),
      leaf(
        'Hide PikPak from Navigation',
        'Hide the PikPak button and tab from the nav bar',
        const ['hide', 'navigation', 'nav', 'tab'],
      ),
      leaf(
        'Enable PikPak Integration',
        'Turn the PikPak integration on or off',
        const ['enable', 'disable', 'turn off', 'integration', 'account'],
      ),
      leaf(
        'Reset Device ID',
        'On the PikPak login screen — issue a fresh device ID if sign-in fails',
        const ['device id', 'reset', 'login problem', 'captcha', 'sign in'],
      ),
    ],
    'webDav': [
      leaf(
        'WebDAV server',
        'Add, edit, test or disconnect a WebDAV server',
        const [
          'add server',
          'another server',
          'server name',
          'server url',
          'seedbox',
          'nas',
          'username',
          'password',
          'app token',
          'save and test',
          'disconnect',
        ],
      ),
      leaf('Enable WebDAV', 'Show WebDAV features in the app', const [
        'enable',
        'disable',
        'integration',
        'cloud',
        'server',
      ]),
      leaf(
        'Hide from navigation',
        'Keep WebDAV configured but remove its tab',
        const ['hide', 'navigation', 'nav', 'tab', 'sidebar'],
      ),
      leaf(
        'Show videos only',
        'Hide non-video files while browsing WebDAV',
        const ['video files', 'filter', 'hide files', 'folders'],
      ),
    ],
    'indexerManagers': [
      leaf(
        'Add or edit an indexer manager',
        'Connect a Jackett or Prowlarr server',
        const [
          'add engine',
          'edit engine',
          'type',
          'name',
          'base url',
          'api key',
          'jackett indexer id',
          'prowlarr',
          'torznab',
          'delete engine',
          'remove manager',
        ],
      ),
      leaf('Categories', 'Limit a manager to Torznab category IDs', const [
        'category',
        'categories',
        '2000',
        '5000',
        'movies',
        'series',
      ]),
      leaf('Max results', 'Maximum results returned by this manager', const [
        'result limit',
        '25',
        '50',
        '100',
        '200',
      ]),
      leaf(
        'Timeout seconds',
        'How long to wait for Jackett or Prowlarr',
        const ['timeout', 'connection', 'slow', '5', '600'],
      ),
      leaf(
        'Enabled',
        'Include or exclude this manager from torrent searches',
        const ['enable', 'disable', 'search source', 'engine'],
      ),
      leaf(
        'Test connection',
        'Check that an indexer manager is reachable',
        const ['test', 'network', 'reachable', 'jackett', 'prowlarr'],
      ),
    ],
    'searchSettings': [
      leaf(
        'Search engine defaults',
        'Which torrent engines searches use by default',
        const ['engine', 'engines', 'default engines', 'torrent', 'sources'],
      ),
      leaf(
        'Indexer managers',
        'Jackett & Prowlarr connections for extra engines',
        const ['jackett', 'prowlarr', 'torznab', 'indexer', 'indexers'],
      ),
    ],
    'filterSettings': [
      leaf('Quality filter', 'Default resolution filter for results', const [
        'quality',
        'resolution',
        '4k',
        '2160p',
        '1080p',
        '720p',
        '480p',
      ]),
      leaf('Rip / Source filter', 'Default release type filter', const [
        'rip',
        'source',
        'web-dl',
        'bluray',
        'remux',
        'brrip',
        'bdrip',
        'hdrip',
        'hdtv',
        'cam',
        'hdcam',
        'telesync',
        'dvdrip',
        'scene',
        'other',
      ]),
      leaf('Language filter', 'Default audio-language filter', const [
        'language',
        'audio',
        'english',
        'hindi',
        'spanish',
        'french',
        'german',
        'russian',
        'chinese',
        'japanese',
        'korean',
        'italian',
        'portuguese',
        'arabic',
        'multi-audio',
      ]),
      leaf('Dynamic range', 'Choose SDR and/or HDR torrent results', const [
        'sdr',
        'hdr',
        'hdr10',
        'hdr10+',
        'dolby vision',
        'dv',
        'hlg',
        'exclude hdr',
        'display',
      ]),
      leaf('Size filter', 'Default file/pack size filter', const [
        'size',
        'gb',
        'mb',
        'file size',
        'tiny',
        'small',
        'high bitrate',
        'very large',
        'remux',
        'huge',
        'under 500 mb',
        'over 40 gb',
      ]),
      leaf('Clear All', 'Remove every saved torrent-search filter', const [
        'clear filters',
        'reset filters',
        'remove filters',
        'defaults',
      ]),
    ],
    'providerSettings': [
      leaf(
        'Default Torrent Provider',
        'Which service torrents are added to',
        const [
          'default provider',
          'ask every time',
          'torbox',
          'real-debrid',
          'premiumize',
          'alldebrid',
          'pikpak',
        ],
      ),
    ],
    'quickPlay': [
      leaf(
        'Play button opens',
        'Play instantly, or pick the source yourself',
        const [
          'auto play',
          'autoplay',
          'quick play',
          'turn off quick play',
          'choose source',
          'pick source',
          'source list',
          'always show sources',
          'always ask',
          'smart',
        ],
      ),
      leaf('Addon Priority', 'Order engines and addons are tried', const [
        'priority',
        'order',
        'addons',
        'engines',
        'reorder',
        'sources',
      ]),
      leaf(
        'Prefer torrents',
        'Torrents first, or addon direct links first',
        const ['torrents', 'direct links', 'addons', 'prefer'],
      ),
      leaf(
        'Streams to try',
        'How many sources Quick Play tries before giving up',
        const [
          'attempts',
          'retries',
          'checking stream',
          'stream count',
          'try next',
          'failover',
          'fallback',
        ],
      ),
      leaf(
        'Prefer season packs',
        'Grab whole seasons, or fetch one episode',
        const ['series', 'packs', 'season pack', 'episode'],
      ),
      leaf(
        'Restore defaults',
        'Reset movie and series rules, switches and priority order',
        const ['reset', 'restore', 'default', 'undo', 'priority'],
      ),
    ],
    'homePage': [
      leaf('Home Rows', 'Choose which rows appear on Home', const [
        'home rows',
        'rows',
        'catalogs',
        'customize',
        'show',
        'hide',
        'arrange',
        'reorder',
        'all on',
        'all off',
        'invert',
        'continue watching',
        'trakt',
        'simkl',
        'mdblist',
        'iptv lists',
        'watchlist',
        'favorites',
        'favourites',
      ]),
      leaf(
        'Hero Source',
        'Choose which catalogs feed the Spotlight hero',
        const [
          'spotlight',
          'hero',
          'first row',
          'surprise me',
          'random',
          'my picks',
          'custom',
          'catalog',
          'reel',
        ],
      ),
      leaf(
        'Landscape Cards',
        'Use wide 16:9 artwork instead of portrait posters',
        const [
          'landscape',
          'wide',
          '16:9',
          'poster',
          'portrait',
          'card orientation',
          'artwork',
        ],
      ),
      leaf('Continue Watching', 'Show recently watched on Home', const [
        'continue watching',
        'recently watched',
        'history',
      ]),
      leaf(
        'Hold to Quick Play',
        'Play immediately when holding a Continue Watching card',
        const [
          'hold',
          'long press',
          'quick play',
          'continue watching',
          'card action',
        ],
      ),
      leaf('Hide Provider Cards', 'Hide debrid status cards on Home', const [
        'hide',
        'provider cards',
        'debrid',
        'status',
      ]),
      leaf(
        'Hide Titles and Ratings',
        'Remove title and rating text from Home cards',
        const ['hide', 'titles', 'ratings', 'cards', 'clean artwork'],
      ),
      leaf(
        'Hide Catalog Add-on Names',
        'Remove source labels beside Home row headings',
        const [
          'hide',
          'catalog',
          'addon',
          'add-on',
          'source label',
          'row heading',
          'home cards',
        ],
      ),
      leaf(
        'Default view',
        'Which view Home opens on (Catalog or Keyword)',
        const [
          'default view',
          'catalog',
          'keyword',
          'landing',
          'opens on',
          'startup',
        ],
        visible: () => !b.isTelevision,
      ),
      leaf(
        'Trailer on Home Spotlight',
        'Play a trailer in the Home and Discover hero',
        const ['trailer', 'spotlight', 'hero', 'ambient', 'autoplay'],
      ),
      leaf(
        'Trailer on Detail Page',
        'Play a trailer behind the movie/series detail page',
        const ['trailer', 'detail page', 'preview', 'backdrop', 'autoplay'],
      ),
      leaf(
        'Trailer Sound',
        'Play ambient Home and detail-page trailers with audio',
        const ['trailer', 'sound', 'audio', 'mute', 'silent', 'ambient'],
      ),
      leaf('Trailer volume', 'Set the volume used by ambient trailers', const [
        'trailer',
        'volume',
        'sound',
        'audio',
        'percent',
        'ambient',
      ]),
      leaf(
        'Native Trailer Surface',
        'Render trailers on a hardware surface for smoother playback',
        const [
          'native',
          'surface',
          'hardware',
          'smooth',
          'stutter',
          'glitch',
          'performance',
          'trailer',
        ],
        visible: () => b.isTelevision,
      ),
    ],
    'tracking': [
      leaf(
        'Hide watched titles',
        'Remove finished movies and shows from Home, Search and Discover',
        const [
          'hide',
          'watched',
          'seen',
          'finished',
          'completed',
          'already watched',
          'filter',
        ],
      ),
      leaf(
        'Scrobble',
        'Choose which connected services record playback',
        const [
          'sync',
          'catalog',
          'watchlist',
          'collection',
          'history',
          'scrobble',
          'refresh',
        ],
      ),
      leaf(
        'Progress source',
        'Choose resume, progress bar and Continue Watching ownership',
        const [
          'sync',
          'catalog',
          'watchlist',
          'plan to watch',
          'history',
          'scrobble',
          'refresh',
        ],
      ),
      leaf(
        'Watched ticks',
        'Choose which histories draw watched ticks on posters',
        const ['watched', 'checkmark', 'tick', 'local', 'trakt', 'simkl'],
      ),
    ],
    'launchAnimation': [
      leaf(
        'Match the app theme',
        'Use the active Look\'s accent colour for the launch ident',
        const [
          'launch',
          'animation',
          'ident',
          'colour',
          'color',
          'accent',
          'look',
          'theme',
        ],
      ),
    ],
    'tvSidebarStyle': [
      leaf(
        'Order & Names',
        'Reorder and rename navigation destinations',
        const [
          'sidebar items',
          'navigation',
          'reorder',
          'arrange',
          'rename',
          'labels',
          'restore default order and names',
          'reset sidebar',
        ],
      ),
    ],
    'desktopSidebarStyle': [
      leaf(
        'Order & Names',
        'Reorder and rename navigation destinations',
        const [
          'sidebar items',
          'navigation',
          'reorder',
          'arrange',
          'rename',
          'labels',
          'restore default order and names',
          'reset sidebar',
        ],
      ),
    ],
    'themeTokens': [
      for (final option in _advancedAppearanceOptions)
        leaf(option.title, option.subtitle, option.keywords),
      leaf(
        'Reset appearance overrides',
        'Return all or one section of advanced tokens to the active Look',
        const [
          'reset',
          'restore',
          'clear changes',
          'follow the look',
          'reset colour',
          'reset ground',
          'reset shape',
          'reset type',
          'reset focus',
          'reset motion',
          'reset surfaces',
          'reset artwork',
          'reset texture',
          'reset feedback',
        ],
      ),
    ],
    'profileAppearance': [
      leaf(
        'Personalized Top Shelf',
        'Show the unlocked active profile on the Apple TV Home Screen',
        const [
          'apple tv',
          'tvos',
          'top shelf',
          'profile',
          'home screen',
          'personalization',
        ],
        visible: () => b.isTvOS,
      ),
    ],
    'player': [
      leaf('Default Player', 'Which player plays videos', const [
        'default player',
        'debrify player',
        'external',
        'external player',
        'built-in',
        'system app chooser',
        'deovr',
      ]),
      leaf('Default Subtitle language', 'Preferred subtitle language', const [
        'subtitle',
        'subtitles',
        'language',
        'captions',
      ]),
      leaf('Default Audio language', 'Preferred audio language / track', const [
        'audio',
        'language',
        'track',
        'dub',
      ]),
      leaf(
        'Subtitle Appearance',
        'Subtitle size, style, color, background & font',
        const [
          'subtitle',
          'size',
          'style',
          'color',
          'background',
          'font',
          'bold',
          'outline',
          'captions',
        ],
      ),
      leaf('Default Aspect Ratio', 'Default video aspect / zoom', const [
        'aspect',
        'ratio',
        'zoom',
        'cinema zoom',
        'fit',
        'fill',
        'contain',
        'cover',
        'fit width',
        'fit height',
        '16:9',
        '4:3',
        '21:9',
        '1:1',
        '3:2',
        '5:4',
      ]),
      leaf(
        'Watch completion thresholds',
        'Choose when locally tracked movies and episodes are marked watched',
        const [
          'watch history',
          'watched',
          'completion',
          'threshold',
          'movie',
          'episode',
          'series',
          'percentage',
          'percent',
          'rewatch',
        ],
      ),
      leaf(
        'Skip intros & credits',
        'Show manual skip buttons when timestamps are available',
        const [
          'skip intro',
          'skip credits',
          'outro',
          'opening',
          'ending',
          'skip segment',
        ],
      ),
      leaf(
        'Timestamp provider',
        'Choose the source for intro and outro timestamps',
        const [
          'auto',
          'skipdb',
          'introdb',
          'theintrodb',
          'provider',
          'timestamp',
          'segments',
        ],
      ),
      leaf(
        'Network & Buffering',
        'Connection patience & stream buffer for slow sources',
        const [
          'network',
          'buffer',
          'buffering',
          'cache',
          'timeout',
          'plex',
          'slow',
          'stall',
          'patience',
          'auto-retry',
          'read-ahead',
        ],
      ),
      leaf(
        'Allow system audio effects',
        'Let equalizer apps process audio (Android)',
        const ['audio effects', 'equalizer', 'wavelet', 'dolby'],
        visible: () => b.isAndroid,
      ),
      leaf(
        'Audio passthrough (AC3 · EAC3 · DTS core)',
        'Bitstream audio to your receiver instead of decoding',
        const [
          'passthrough',
          'bitstream',
          'dts',
          'ac3',
          'dolby',
          'receiver',
          'avr',
        ],
        visible: () => b.isAndroid,
      ),
      leaf(
        'Multichannel audio (LPCM over HDMI)',
        'Surround tracks as 5.1/7.1 PCM on capable receivers',
        const [
          'multichannel',
          'surround',
          '5.1',
          '7.1',
          'lpcm',
          'audio channels',
        ],
        visible: () => b.isTvOS || b.isIosMobile,
      ),
      leaf(
        'Force software video decoding',
        'Apple TV compatibility option for videos that render wrong',
        const [
          'software decoding',
          'compatibility',
          'blue screen',
          'wrong colors',
          'hardware decoding',
          '10-bit',
        ],
        visible: () => b.isTvOS,
      ),
      leaf(
        'Force stereo audio',
        'Always downmix Apple TV playback to two channels',
        const [
          'stereo',
          'downmix',
          '2 channels',
          'surround',
          'noisy',
          'distorted',
          'receiver',
          'tvos',
        ],
        visible: () => b.isTvOS,
      ),
      leaf(
        'Use the previous audio engine',
        'Apple TV audio compatibility option',
        const [
          'legacy audio',
          'old audio engine',
          'audio output',
          'compatibility',
          'atmos',
          'no sound',
          'tvos',
        ],
        visible: () => b.isTvOS,
      ),
      leaf(
        'IPTV decoder',
        'Switch to software decoding when a channel freezes',
        const [
          'iptv',
          'decoder',
          'software',
          'hardware',
          'freeze',
          'frozen',
          'audio only',
          'no picture',
        ],
        visible: () => b.isAndroid && b.isAndroidTv,
      ),
      leaf(
        'Video renderer',
        'Choose the Android phone/tablet video output path',
        const [
          'renderer',
          'mediacodec',
          'direct surface',
          'battery',
          'performance',
          'hardware decoding',
        ],
        visible: () => b.isAndroid && !b.isAndroidTv,
      ),
      leaf(
        'Night Mode',
        'Boost quiet sounds for late-night viewing',
        const [
          'night',
          'quiet',
          'volume',
          'dynamic range compression',
          'sleeping baby',
          'low',
          'medium',
          'high',
          'higher',
          'extreme',
          'max',
          'off',
        ],
        visible: () => b.isAndroid && b.isAndroidTv,
      ),
      leaf(
        'Auto-sync addon subtitles',
        'Align downloaded subtitles to the audio automatically',
        const [
          'subtitle',
          'sync',
          'auto',
          'align',
          'timing',
          'offset',
          'experimental',
        ],
        visible: () => b.supportsSubtitleAutoSync,
      ),
      leaf(
        'Open the player in portrait',
        'Start videos upright instead of turning the phone landscape',
        const [
          'portrait',
          'landscape',
          'orientation',
          'rotate',
          'rotation',
          'vertical',
          'horizontal',
        ],
        visible: () => b.isPhone,
      ),
      leaf(
        'Preferred external player',
        'Choose the external player app',
        [
          'external',
          'player app',
          'system default',
          'custom command',
          'custom url scheme',
          ...b.extraPlayerKeywords(),
        ],
        visible: () => b.preferredExternalPlayerSupported,
      ),
      leaf(
        'Custom player command',
        'Custom launch command or URL scheme for an external player',
        const [
          'custom command',
          'url scheme',
          'launch',
          'arguments',
          'external',
          'save command',
          'command template',
        ],
        visible: () => b.customPlayerCommandSupported,
      ),
      leaf(
        'Import Custom Font',
        'Add your own TTF/OTF font for subtitles',
        const [
          'font',
          'ttf',
          'otf',
          'import font',
          'custom font',
          'remove font',
          'delete font',
          'subtitle',
        ],
      ),
      leaf(
        'VR / DeoVR format',
        'Screen type, stereo mode and format detection for DeoVR',
        const [
          'vr',
          'deovr',
          'stereo',
          'screen type',
          '180',
          '360',
          'sbs',
          'side by side',
          'over under',
          'format',
          'auto-detect format from filename',
          'show format selection dialog',
        ],
        visible: () => b.isAndroid,
      ),
    ],
    'debrifyTv': [
      leaf(
        'Keyword Threshold',
        'Choose when Debrify TV fetches more or fewer results per keyword',
        const ['keyword', 'threshold', 'results', 'fetch', 'global tv mode'],
      ),
      leaf('Batch Size', 'Number of keywords processed in each batch', const [
        'batch',
        'keywords',
        'performance',
        'global tv mode',
      ]),
      leaf(
        'Min Torrents Per Keyword',
        'Skip keywords with fewer torrent results',
        const ['minimum', 'torrents', 'keyword', 'skip', 'result count'],
      ),
      leaf(
        'Max Keywords (Quick Play)',
        'Limit the keywords used in Quick Play mode',
        const ['maximum', 'keyword limit', 'quick play', 'performance'],
      ),
      leaf(
        'Avoid NSFW Content',
        'Filter adult content out of Debrify TV results',
        const ['nsfw', 'adult', 'safe', 'filter', 'content'],
      ),
      leaf(
        'Prepare Torrents in Background',
        'Pre-add upcoming Real-Debrid and AllDebrid torrents',
        const [
          'background',
          'prefetch',
          'pre-fetch',
          'prepare',
          'faster playback',
          'real-debrid',
          'alldebrid',
        ],
      ),
      leaf(
        'Engine TV Mode',
        'Enable or disable each search engine for Debrify TV',
        const ['engine', 'tv mode enabled', 'tv mode disabled', 'toggle'],
      ),
      leaf(
        'Small Channel Limit',
        'Maximum results for each engine in small channel mode',
        const ['small channel', 'result limit', 'max results', 'engine'],
      ),
      leaf(
        'Large Channel Limit',
        'Maximum results for each engine in large channel mode',
        const ['large channel', 'result limit', 'max results', 'engine'],
      ),
      leaf(
        'Quick Play Limit',
        'Maximum results for each engine in Quick Play mode',
        const ['quick play', 'result limit', 'max results', 'engine'],
      ),
      leaf(
        'Reset to Defaults',
        'Restore the default Debrify TV engine settings',
        const ['reset', 'defaults', 'restore', 'engines'],
      ),
    ],
    'stremioTv': [
      leaf(
        'Rotation Interval',
        'How often the now-playing item changes on movie channels',
        const ['rotation', 'interval', 'minutes', 'movie', 'change', 'shuffle'],
      ),
      leaf(
        'Series Rotation Interval',
        'How often the episode changes on series channels',
        const [
          'series',
          'episode',
          'rotation',
          'interval',
          'minutes',
          'change',
          'schedule',
        ],
      ),
      leaf(
        'Preferred Quality',
        'Prioritize streams matching this quality',
        const ['quality', '4k', '2160p', '1080p', '720p', 'resolution'],
      ),
      leaf(
        'Debrid Provider',
        'Which provider resolves Stremio TV torrent streams',
        const ['debrid', 'provider', 'auto', 'real-debrid', 'torbox', 'pikpak'],
      ),
      leaf(
        'Try torrents first',
        'Resolve torrents via debrid before trying direct streams',
        const ['torrents first', 'direct', 'stream', 'order', 'fallback'],
      ),
      leaf(
        'Random Episodes',
        'Pick episodes at random on series channels',
        const ['random', 'shuffle', 'episodes', 'series'],
      ),
      leaf(
        'Start Position',
        'Where playback begins within the current slot',
        const ['start', 'position', 'beginning', 'slot progress', 'resume'],
      ),
      leaf(
        'Hide Currently Playing',
        'Blur the poster and hide details for a surprise',
        const ['hide', 'spoiler', 'surprise', 'blur', 'now playing'],
      ),
      leaf('Auto-refresh', 'Refresh Stremio TV channels automatically', const [
        'auto refresh',
        'refresh',
        'update',
        'channels',
      ]),
    ],
    'iptvPlaylists': [
      leaf(
        'Add a source',
        'Add an M3U link, an Xtream login, or a local file',
        const [
          'add',
          'source',
          'playlist',
          'm3u',
          'm3u8',
          'xtream',
          'login',
          'url',
          'file',
          'import',
          'from url',
          'from file',
          'browse files',
          'name your playlist',
        ],
        onTap: b.openIptvAddSource,
      ),
      leaf(
        'Edit source',
        'Change a playlist name, URL, guide or Xtream credentials',
        const [
          'edit playlist',
          'rename source',
          'm3u url',
          'server',
          'username',
          'password',
          'xtream',
          'xmltv',
          'epg',
        ],
      ),
      leaf(
        'Remove source',
        'Delete an IPTV source while keeping lists and watch history',
        const [
          'remove playlist',
          'delete source',
          'disconnect',
          'shared source',
          'keep lists',
          'watch history',
        ],
      ),
      leaf(
        'Guide (EPG) source',
        'Provider guide or a custom XMLTV URL per source',
        const [
          'epg',
          'guide',
          'xmltv',
          'tv guide',
          'programme',
          'schedule',
          'now next',
          'custom guide',
        ],
      ),
      leaf(
        'Hidden categories',
        'Bring back categories you hid on the IPTV page',
        const [
          'hidden',
          'hide',
          'unhide',
          'category',
          'categories',
          'adult',
          'restore',
          'show all',
          'hide all',
          'filter categories',
          'live tv',
          'movies',
          'series',
        ],
      ),
      leaf('Create list', 'Make a custom list for saved IPTV channels', const [
        'channel lists',
        'new list',
        'saved channels',
        'favorites',
        'favourites',
        'collection',
      ]),
      leaf(
        'Manage channel lists',
        'Rename, reorder or delete a custom IPTV list',
        const [
          'rename list',
          'move up',
          'move down',
          'reorder',
          'delete list',
          'remove list',
          'channels are kept',
        ],
      ),
      leaf(
        'Channel order',
        'Arrange channels inside Favorites and saved lists',
        const [
          'channel order',
          'manual order',
          'sort favorites',
          'sort favourites',
          'reorder channels',
          'dpad',
        ],
        onTap: b.openIptvChannelOrder,
      ),
      leaf('Default playlist', 'Which source loads when you open IPTV', const [
        'default',
        'playlist',
        'source',
        'opens',
        'preferred',
      ]),
      leaf('Refresh now', 'Re-fetch channels and rebuild the catalog', const [
        'refresh',
        'refresh playlist',
        'reload',
        'update',
        'rebuild',
        'catalog',
        're-fetch',
        'missing channels',
      ]),
      leaf(
        'Start on a channel',
        'Open straight into live TV when Debrify starts',
        const [
          'startup channel',
          'startup',
          'boot',
          'launch',
          'autoplay',
          'live tv',
        ],
      ),
      leaf(
        'Startup channel choice',
        'Start on the last watched channel or a specific channel',
        const [
          'last watched channel',
          'specific channel',
          'choose channel',
          'change channel',
          'pinned channel',
          'startup mode',
        ],
      ),
      leaf(
        'Track movies and series',
        'Add IPTV on-demand playback to Continue Watching',
        const [
          'continue watching',
          'iptv history',
          'resume',
          'vod',
          'movies',
          'series',
          'shelf',
        ],
      ),
      leaf(
        'Background recording engine',
        'Keep recordings running when you zap or leave the app',
        const [
          'background',
          'engine',
          'recording',
          'dvr',
          'scheduled',
          'player-tied',
        ],
        visible: () => b.recordingSearchable,
      ),
      leaf(
        'Simultaneous recordings',
        'How many recordings can run at once',
        const [
          'simultaneous',
          'concurrent',
          'parallel',
          'at once',
          'connections',
          'limit',
        ],
        visible: () => b.recordingSearchable,
      ),
      leaf(
        'Battery optimization',
        'Exclude Debrify so recordings survive doze',
        const [
          'battery',
          'doze',
          'optimization',
          'background',
          'killed',
          'stops',
        ],
        visible: () => b.recordingSearchable,
      ),
    ],
    'recordings': [
      leaf(
        'Schedule a recording',
        'Record a channel at a set date and time',
        const [
          'schedule',
          'timer',
          'record later',
          'date',
          'start time',
          'alarm',
        ],
        visible: () => b.recordingSupported,
      ),
      leaf(
        'Recordings library',
        'Your recorded files, and where they are saved',
        const [
          'library',
          'recorded',
          'files',
          'folder',
          'storage',
          'downloads',
          'delete recording',
        ],
        visible: () => b.recordingSupported,
      ),
    ],
    'switchProfile': [
      leaf(
        'Ask who\'s watching at startup',
        'Show the profile picker whenever Debrify opens',
        const [
          'always ask',
          'profile behavior',
          'profile picker',
          'startup',
          'launch',
          'who is watching',
        ],
        visible: () => b.profileCommitted,
      ),
      leaf(
        'Send profiles to TV',
        'Transfer profiles, connections and PINs to another device',
        const [
          'household',
          'transfer',
          'pair',
          'remote',
          'connections',
          'pins',
          'setup',
        ],
        visible: () => b.profileCommitted,
      ),
      leaf(
        'Manage profiles',
        'Create, edit, switch, enable, disable or delete a profile',
        const [
          'current profile',
          'other profiles',
          'create profile',
          'edit profile',
          'switch profile',
          'delete profile',
          'disable profile',
          'enable profile',
          'name',
          'avatar',
          'save name and avatar',
          'choose image or gif',
          'pin',
          'pin protection',
          'set pin',
          'change pin',
          'remove pin',
          'access',
          'admin',
          'member',
          'kid',
          'profile diagnostics',
        ],
        visible: () => b.profileCommitted,
      ),
    ],
    'mdblist': [
      leaf(
        'MDBList API Key',
        'Connect MDBList and browse your lists',
        const [
          'api key',
          'add api key',
          'logout',
          'lists',
          'liked',
          'supporter',
          'usage',
          'mdblist preferences',
          'open mdblist.com/preferences',
        ],
        visible: () => b.mdblistEnabled,
      ),
    ],
    'remote': [
      leaf(
        'Control another device',
        'Use this device as a remote, or send your setup to another',
        const [
          'remote',
          'control',
          'pair',
          'wifi',
          'send setup',
          'push addons',
          'handoff',
          'd-pad',
          'paired remote devices',
          'manage pairing',
        ],
      ),
      leaf(
        'Receive from another device',
        'Let another device control this one or send it addons & channels',
        const [
          'receive',
          'target',
          'pair',
          'import setup',
          'addons',
          'channels',
          'sessions',
          'paired remote devices',
          'manage pairing',
        ],
      ),
    ],
  };
}

const _advancedAppearanceOptions =
    <({String title, String subtitle, List<String> keywords})>[
      (
        title: 'Accent',
        subtitle: 'The colour used to mean “this one”',
        keywords: ['color', 'colour', 'theme', 'selected'],
      ),
      (
        title: 'Focus',
        subtitle: 'The colour of the cursor',
        keywords: ['cursor', 'focus color', 'focus colour', 'dpad'],
      ),
      (
        title: 'Progress',
        subtitle: 'Progress bars and watched marks',
        keywords: ['watched', 'marks', 'bar', 'state', 'colour', 'color'],
      ),
      (
        title: 'Callout',
        subtitle: 'Badges and highlights',
        keywords: ['badge', 'highlight', 'colour', 'color'],
      ),
      (
        title: 'Background',
        subtitle: 'The page behind everything',
        keywords: ['ground', 'surface', 'page', 'colour', 'color'],
      ),
      (
        title: 'Text',
        subtitle: 'The ink drawn over the background',
        keywords: ['ink', 'foreground', 'readability', 'colour', 'color'],
      ),
      (
        title: 'Corners',
        subtitle: 'How round cards are',
        keywords: ['radius', 'round', 'square', 'shape', 'cards'],
      ),
      (
        title: 'Buttons',
        subtitle: 'How round buttons and pills are',
        keywords: ['pill radius', 'round', 'square', 'shape'],
      ),
      (
        title: 'Titles',
        subtitle: 'The font used for display titles',
        keywords: ['display font', 'typeface', 'typography'],
      ),
      (
        title: 'Body',
        subtitle: 'The font used for everything else',
        keywords: ['body font', 'typeface', 'typography'],
      ),
      (
        title: 'Cursor',
        subtitle: 'How a focused item is expressed',
        keywords: [
          'focus expression',
          'ring',
          'scale',
          'lift',
          'invert',
          'flood',
          'parallax',
        ],
      ),
      (
        title: 'Character',
        subtitle: 'The tempo of app motion',
        keywords: ['motion', 'animation', 'standard', 'snap', 'glide'],
      ),
      (
        title: 'Entrances',
        subtitle: 'How new content arrives',
        keywords: ['motion', 'animation', 'transition'],
      ),
      (
        title: 'When idle',
        subtitle: 'What happens when interaction stops',
        keywords: ['idle policy', 'motion', 'animation'],
      ),
      (
        title: 'Separation',
        subtitle: 'How one surface is distinguished from another',
        keywords: ['space', 'rule', 'glass', 'fill', 'panel', 'surface'],
      ),
      (
        title: 'Scrims',
        subtitle: 'The fade behind text on artwork',
        keywords: ['scrim', 'gradient', 'artwork', 'readability'],
      ),
      (
        title: 'Frames',
        subtitle: 'How posters are edged',
        keywords: ['artwork', 'poster', 'border', 'frame'],
      ),
      (
        title: 'Grade',
        subtitle: 'Colour treatment over artwork',
        keywords: ['artwork', 'color grade', 'colour grade', 'filter'],
      ),
      (
        title: 'Room colour',
        subtitle: 'How much the page borrows from selected artwork',
        keywords: ['reactive room', 'artwork', 'ambient', 'color', 'colour'],
      ),
      (
        title: 'Accent from artwork',
        subtitle: 'Let poster colour replace the app accent',
        keywords: ['artwork accent', 'poster', 'dynamic color', 'colour'],
      ),
      (
        title: 'Film grain',
        subtitle: 'Texture layered over the interface',
        keywords: ['grain', 'noise', 'texture', 'cinema'],
      ),
      (
        title: 'Sheen',
        subtitle: 'Highlight along the top of a surface',
        keywords: ['texture', 'highlight', 'surface'],
      ),
      (
        title: 'Vignette',
        subtitle: 'Darkening toward the screen edges',
        keywords: ['texture', 'dark edges', 'artwork'],
      ),
      (
        title: 'Focus glow',
        subtitle: 'Halo around the cursor',
        keywords: ['bloom', 'glow', 'focus', 'cursor', 'halo'],
      ),
      (
        title: 'Sound and haptics',
        subtitle: 'What a press feels and sounds like',
        keywords: ['feedback', 'sound', 'haptic', 'vibration'],
      ),
      (
        title: 'While loading',
        subtitle: 'How not-yet-arrived content appears',
        keywords: ['skeleton', 'loading', 'placeholder', 'shimmer'],
      ),
    ];
