import 'package:flutter/material.dart';

import '../../services/play_loader_style.dart';
import '../../services/tv_motion_profile.dart';
import '../profiles/profile_wall_screen.dart';
import 'debrify_tv_style_page.dart';
import 'desktop_sidebar_style_page.dart';
import 'detail_page_style_page.dart';
import 'discover_layout_page.dart';
import 'iptv_style_page.dart';
import 'layout_options.dart';
import 'layout_row_writers.dart';
import 'parents_guide_style_page.dart';
import 'player_dock_page.dart';
import 'player_guide_style_page.dart';
import 'settings_page_registry.dart';
import 'settings_page_spec.dart';
import 'settings_search_leaves.dart';
import 'tv_home_style_page.dart';
import 'tv_sidebar_style_page.dart';
import 'widgets/settings_widgets.dart';

const kCatConnections = 'Connections';
const kCatLayout = 'Layout';
const kCatTheme = 'Theme';
const kCatDevices = 'Devices';
const kCatProfiles = 'Profiles';
const kCatData = 'Data & Backup';
const kCatAbout = 'About';
const kCatDanger = 'Danger Zone';
const kCatAddons = 'Addons';
const kCatStremioTv = 'Stremio TV';

const kGroupStorageProviders = 'Storage Providers';
const kGroupSearchPlayback = 'Search & Playback';
const kGroupIptv = 'IPTV';
const kGroupTracking = 'Tracking';
const kGroupAppStructure = 'App Structure';
const kGroupDetailBrowsing = 'Detail & Browsing';
const kGroupLiveTvLooks = 'Live TV & IPTV Looks';
const kGroupPlayerLooks = 'Player Looks';
const kGroupScreen = 'Screen';
const kGroupDownloads = 'Downloads';
const kGroupMaintenance = 'Maintenance';
const kGroupBackup = 'Backup & Restore';
const kGroupDiagnostics = 'Diagnostics';
const kGroupUpdates = 'Updates';
const kGroupCommunity = 'Community & Support';

/// Production settings catalog. Adding a page is one [SettingsPageSpec]
/// in this list; phone, desktop, TV and search all iterate it.
List<SettingsPageSpec> buildSettingsPages(SettingsPageBindings b) {
  final leaves = settingsLeavesByPage(b);

  SettingsPageSpec page({
    required String id,
    required SettingsRowContent row,
    required String category,
    Future<void> Function()? opener,
    List<String> keywords = const [],
    bool phone = true,
    bool desktop = true,
    bool tv = true,
    bool search = true,
    int phoneOrder = 100,
    int desktopOrder = 100,
    int tvOrder = 100,
    String? phoneGroup,
    String? desktopGroup,
    String? tvGroup,
    SettingsRowKind kind = SettingsRowKind.tile,
    SettingsRowKind? phoneKind,
    SettingsRowKind? desktopKind,
    SettingsRowKind? tvKind,
    bool destructive = false,
    bool Function()? visible,
    bool Function(SettingsLayoutSurface surface)? visibleOn,
    bool Function()? searchVisible,
    String Function()? titleOf,
    String Function()? subtitleOf,
    Widget? Function()? trailingOf,
    String? tag,
    bool Function()? toggleValue,
    ValueChanged<bool>? onToggle,
    String? leafPageName,
    SettingsLayoutOptions? layoutOptions,
  }) {
    return SettingsPageSpec(
      id: id,
      row: row,
      category: category,
      opener: opener,
      keywords: keywords,
      leaves: leaves[id] ?? const [],
      phone: phone,
      desktop: desktop,
      tv: tv,
      search: search,
      phoneOrder: phoneOrder,
      desktopOrder: desktopOrder,
      tvOrder: tvOrder,
      phoneGroup: phoneGroup,
      desktopGroup: desktopGroup,
      tvGroup: tvGroup,
      kind: kind,
      phoneKind: phoneKind,
      desktopKind: desktopKind,
      tvKind: tvKind,
      destructive: destructive,
      visible: visible,
      visibleOn: visibleOn,
      searchVisible: searchVisible,
      titleOf: titleOf,
      subtitleOf: subtitleOf,
      trailingOf: trailingOf,
      tag: tag,
      toggleValue: toggleValue,
      onToggle: onToggle,
      leafPageName: leafPageName,
      layoutOptions: layoutOptions,
    );
  }

  /// An inline Screen-layouts option set. [write] is the opener page's own
  /// setter path ([LayoutRowWriters]); the screen is then told so the value
  /// behind [SettingsPageBindings.layoutValues] follows without a page pop.
  SettingsLayoutOptions layouts({
    required String rowId,
    required List<LayoutOption> options,
    required String Function() current,
    required Future<void> Function(String value) write,
    String? moreLabel,
    Future<void> Function()? onMore,
    String Function()? variant,
  }) {
    return SettingsLayoutOptions(
      rowId: rowId,
      options: options,
      current: current,
      apply: (value) async {
        await write(value);
        b.onLayoutApplied(rowId, value);
      },
      moreLabel: moreLabel,
      onMore: onMore,
      variant: variant,
    );
  }

  return [
    // --- Layout: App Structure ---
    // Screen-layouts rows: the options render inline (kind: options) and the
    // opener is kept for SEARCH only — a search hit still opens the picker
    // page, which is also where Home Screen and IPTV reach some of them.
    page(
      id: 'tvHomeStyle',
      row: SettingsRows.tvHomeStyle,
      category: kCatLayout,
      opener: b.openTvHomeStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'tvHomeStyle',
        // TV-only row, so every layout is offered; the off-TV narrowing to
        // Classic/Spotlight belongs to the page Home Screen opens.
        options: [
          for (final c in kTvHomeStyleChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.tvHomeStyle,
        write: LayoutRowWriters.tvHomeStyle,
      ),
      phone: false,
      desktop: false,
      tv: true,
      search: true,
      tvOrder: 10,
      tvGroup: kGroupAppStructure,
      subtitleOf: () => b.tvHomeStyleLabel,
      keywords: [
        'home',
        'layout',
        'home screen',
        'canvas',
        'spotlight',
        'shelf',
        'classic',
        'rows',
        'redesign',
        'view',
        'display',
        ...b.extraTvHomeStyleKeywords(),
      ],
    ),
    page(
      id: 'discoverLayout',
      row: SettingsRows.discoverLayout,
      category: kCatLayout,
      opener: b.openDiscoverLayout,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'discoverLayout',
        options: [
          for (final c in kDiscoverLayoutChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.discoverLayout,
        write: LayoutRowWriters.discoverLayout,
      ),
      phone: false,
      desktop: false,
      tv: true,
      search: true,
      tvOrder: 20,
      tvGroup: kGroupAppStructure,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.discoverLayoutLabel,
      keywords: [
        'discover',
        'layout',
        'stage',
        'grid',
        'browse',
        'shelf',
        'catalog',
        'view',
        'posters',
        'display',
        ...b.extraDiscoverLayoutKeywords(),
      ],
    ),
    // Merged tvSidebarStyle (6 TV options) + desktopSidebarStyle (2
    // phone/tablet options) + the old Home & Display desktop tile — three
    // rows for what is conceptually one setting, now one row whose kind and
    // layoutOptions branch on surface at catalog-build time. Production
    // never renders two surfaces from one build (a device is phone,
    // desktop or Android TV, never more than one at once), so reading
    // b.isAndroidTv here is safe; tests that need a specific surface must
    // construct bindings with that flag set accordingly. "Order & Names"
    // still opens SidebarCustomizationPage directly from inside each
    // destination page.
    page(
      id: 'sidebarStyle',
      row: SettingsRows.tvSidebarStyle,
      category: kCatLayout,
      opener: () =>
          b.isAndroidTv ? b.openTvSidebarStyle() : b.openDesktopSidebarStyle(),
      kind: SettingsRowKind.tile,
      phoneKind: SettingsRowKind.options,
      tvKind: SettingsRowKind.options,
      layoutOptions: b.isAndroidTv
          ? layouts(
              rowId: 'sidebarStyle',
              options: [
                for (final c in kTvSidebarStyleChoices)
                  LayoutOption(c.value, c.label, c.subtitle),
              ],
              current: () => b.layoutValues.tvSidebarStyle,
              write: LayoutRowWriters.tvSidebarStyle,
            )
          : layouts(
              rowId: 'sidebarStyle',
              options: [
                for (final c in kDesktopSidebarStyleChoices)
                  LayoutOption(c.value, c.label, c.subtitle),
              ],
              current: () => b.layoutValues.desktopSidebarStyle,
              write: LayoutRowWriters.desktopSidebarStyle,
            ),
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      phoneGroup: kGroupAppStructure,
      desktopGroup: kGroupAppStructure,
      tvGroup: kGroupAppStructure,
      // The TV rail is Android-TV-only, so the tv:true flag alone already
      // gates that surface correctly; phone/desktop hide on tvOS, matching
      // the old desktopSidebarStyle row's visibility exactly.
      visibleOn: (s) => s == SettingsLayoutSurface.tv || !b.isTelevision,
      leafPageName: 'Sidebar',
      subtitleOf: () =>
          b.isAndroidTv ? b.tvSidebarStyleLabel : b.desktopSidebarStyleLabel,
      keywords: [
        'sidebar',
        'nav',
        'navigation',
        'rail',
        'menu',
        'ghost',
        'island',
        'marquee',
        'badge',
        'dock',
        'pill',
        'desktop',
        'tablet',
        'ipad',
        'order and names',
        'rename sidebar',
        ...b.extraTvSidebarKeywords(),
        ...b.extraDesktopSidebarKeywords(),
      ],
    ),
    // Merged the desktop tile (opened a dialog) and the phone inline chips —
    // both already wrote the same phone_nav_style pref through the same
    // b.openNavigation dialog, so this is the simple case: one row.
    page(
      id: 'navigationStyle',
      row: SettingsRows.navigationStyle,
      category: kCatLayout,
      opener: b.openNavigation,
      kind: SettingsRowKind.tile,
      phoneKind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'navigationStyle',
        // The Navigation dialog's two options, verbatim.
        options: const [
          LayoutOption(
            'classic',
            'Classic bar',
            'Bottom tabs — Home, three slots you pick, More holds the '
                'rest',
          ),
          LayoutOption(
            'floating',
            'Floating button',
            'The glass button with the expanding menu',
          ),
        ],
        current: () => b.layoutValues.phoneNavStyle,
        write: LayoutRowWriters.phoneNavStyle,
      ),
      tv: false,
      phoneOrder: 40,
      desktopOrder: 40,
      phoneGroup: kGroupAppStructure,
      desktopGroup: kGroupAppStructure,
      visible: () => !b.isTelevision,
      subtitleOf: () => b.phoneNavStyleLabel,
      keywords: const [
        'navigation',
        'nav',
        'bottom bar',
        'tabs',
        'floating',
        'classic',
        'menu',
      ],
    ),
    page(
      id: 'homePage',
      row: SettingsRows.homePage,
      category: kCatLayout,
      opener: b.openHomePage,
      phoneOrder: 50,
      desktopOrder: 50,
      tvOrder: 50,
      phoneGroup: kGroupAppStructure,
      desktopGroup: kGroupAppStructure,
      tvGroup: kGroupAppStructure,
      keywords: const [
        'home page',
        'default view',
        'startup',
        'landing',
        'tab',
      ],
    ),
    page(
      id: 'collections',
      row: SettingsRows.collections,
      category: kCatLayout,
      opener: b.openCollections,
      phoneOrder: 60,
      desktopOrder: 60,
      tvOrder: 60,
      phoneGroup: kGroupAppStructure,
      desktopGroup: kGroupAppStructure,
      tvGroup: kGroupAppStructure,
      keywords: const [
        'collections',
        'collection',
        'nuvio',
        'xperience',
        'folders',
        'import json',
      ],
    ),
    page(
      id: 'titleRatingsVisibility',
      row: SettingsRows.titleRatingsVisibility,
      category: kCatLayout,
      opener: b.openTitleRatingsVisibility,
      phoneOrder: 70,
      desktopOrder: 70,
      tvOrder: 70,
      phoneGroup: kGroupAppStructure,
      desktopGroup: kGroupAppStructure,
      tvGroup: kGroupAppStructure,
      keywords: const [
        'titles',
        'ratings',
        'poster titles',
        'hide titles',
        'show titles',
        'show ratings',
        'home',
        'discover',
      ],
    ),

    // --- Layout: Detail & Browsing ---
    page(
      id: 'detailPageStyle',
      row: SettingsRows.detailPageStyle,
      category: kCatLayout,
      opener: b.openDetailPageStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'detailPageStyle',
        // Only what this build can draw, and the active option is the
        // NARROWED value — the same two rules the picker page applies.
        options: [
          for (final c in kDetailPageStyleChoices)
            if (kDetailPageStylesShipped.contains(c.value))
              LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () =>
            effectiveDetailPageStyle(b.layoutValues.detailPageStyle),
        write: LayoutRowWriters.detailPageStyle,
      ),
      phoneOrder: 110,
      desktopOrder: 110,
      tvOrder: 110,
      phoneGroup: kGroupDetailBrowsing,
      desktopGroup: kGroupDetailBrowsing,
      tvGroup: kGroupDetailBrowsing,
      subtitleOf: () => b.detailPageStyleLabel,
      keywords: [
        'details',
        'detail',
        'page',
        'layout',
        'style',
        'theme',
        'look',
        'movie',
        'series',
        'show',
        'episodes',
        'episode list',
        'marquee',
        'dossier',
        'broadsheet',
        'stage',
        'filmstrip',
        'console',
        'classic',
        ...b.extraDetailPageKeywords(),
      ],
    ),
    page(
      id: 'parentsGuideStyle',
      row: SettingsRows.parentsGuideStyle,
      category: kCatLayout,
      opener: b.openParentsGuideStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'parentsGuideStyle',
        options: [
          for (final c in kParentsGuideStyleChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.parentsGuideStyle,
        write: LayoutRowWriters.parentsGuideStyle,
      ),
      phoneOrder: 120,
      desktopOrder: 120,
      tvOrder: 120,
      phoneGroup: kGroupDetailBrowsing,
      desktopGroup: kGroupDetailBrowsing,
      tvGroup: kGroupDetailBrowsing,
      subtitleOf: () => b.parentsGuideStyleLabel,
      keywords: [
        'parents',
        'parental',
        'guide',
        'advisory',
        'content rating',
        'severity',
        'compass',
        'classic',
        'family',
        ...b.extraParentsGuideKeywords(),
      ],
    ),
    page(
      id: 'discoverDefault',
      row: SettingsRows.discoverDefault,
      category: kCatLayout,
      opener: b.openDiscover,
      phoneOrder: 130,
      desktopOrder: 130,
      tvOrder: 130,
      phoneGroup: kGroupDetailBrowsing,
      desktopGroup: kGroupDetailBrowsing,
      tvGroup: kGroupDetailBrowsing,
      keywords: const [
        'remember last',
        'default source',
        'continue watching',
        'trakt',
        'simkl',
        'stremio addon',
        'movie tag',
        'series tag',
      ],
    ),

    // --- Layout: Live TV & IPTV Looks ---
    page(
      id: 'iptvAppearance',
      row: SettingsRows.iptvAppearance,
      category: kCatLayout,
      opener: b.openIptvStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'iptvAppearance',
        options: [
          for (final c in kIptvStyleChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.iptvStyle,
        write: LayoutRowWriters.iptvStyle,
      ),
      phoneOrder: 210,
      desktopOrder: 210,
      tvOrder: 210,
      phoneGroup: kGroupLiveTvLooks,
      desktopGroup: kGroupLiveTvLooks,
      tvGroup: kGroupLiveTvLooks,
      visibleOn: (s) =>
          s == SettingsLayoutSurface.tv ? true : b.iptvAppearanceSearchable,
      searchVisible: () => b.iptvAppearanceSearchable,
      subtitleOf: () => b.iptvStyleLabel,
      keywords: [
        'iptv',
        'style',
        'theme',
        'look',
        'skin',
        'appearance',
        'command center',
        'first edition',
        'master control',
        'cockpit',
        'premium',
        'live tv',
        'dvr',
        ...b.extraIptvStyleKeywords(),
      ],
    ),
    page(
      id: 'debrifyTvAppearance',
      row: SettingsRows.debrifyTvAppearance,
      category: kCatLayout,
      opener: b.openDebrifyTvStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'debrifyTvAppearance',
        options: [
          for (final c in kDebrifyTvStyleChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.debrifyTvStyle,
        write: LayoutRowWriters.debrifyTvStyle,
      ),
      phoneOrder: 220,
      desktopOrder: 220,
      tvOrder: 220,
      phoneGroup: kGroupLiveTvLooks,
      desktopGroup: kGroupLiveTvLooks,
      tvGroup: kGroupLiveTvLooks,
      subtitleOf: () => b.debrifyTvStyleLabel,
      keywords: [
        'debrify tv',
        'channels',
        'channel grid',
        'rail',
        'stage',
        'spotlight',
        'style',
        'layout',
        'look',
        'appearance',
        ...b.extraDebrifyTvStyleKeywords(),
      ],
    ),
    page(
      id: 'playerGuideStyle',
      row: SettingsRows.playerGuideStyle,
      category: kCatLayout,
      opener: b.openPlayerGuideStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'playerGuideStyle',
        // Spotlight is tvOS's idiom; the native Android TV player falls
        // back to Classic for it, so it is not offered there — the page's
        // own platform rule.
        options: [
          for (final c in kPlayerGuideStyleChoices)
            if (c.value != 'spotlight' || !b.isAndroidTv)
              LayoutOption(c.value, c.label, c.subtitle),
        ],
        current: () => b.layoutValues.playerGuideStyle,
        write: LayoutRowWriters.playerGuideStyle,
      ),
      phoneOrder: 230,
      desktopOrder: 230,
      tvOrder: 230,
      phoneGroup: kGroupLiveTvLooks,
      desktopGroup: kGroupLiveTvLooks,
      tvGroup: kGroupLiveTvLooks,
      subtitleOf: () => b.playerGuideStyleLabel,
      keywords: [
        'iptv',
        'player',
        'guide',
        'zap',
        'banner',
        'style',
        'theme',
        'look',
        'skin',
        'cinema glass',
        'midnight edition',
        'master control',
        'classic',
        'live tv',
        'dvr',
        ...b.extraPlayerGuideKeywords(),
      ],
    ),
    page(
      id: 'debrifyTvPlayer',
      row: SettingsRows.debrifyTvPlayer,
      category: kCatLayout,
      opener: b.openDebrifyTvPlayerStyle,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 240,
      tvGroup: kGroupLiveTvLooks,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? b.isAndroidTv : false,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.debrifyTvPlayerStyleLabel,
      keywords: [
        'debrify tv',
        'magic tv',
        'channel',
        'player',
        'network',
        'cinema',
        'guide',
        'spotlight',
        'prestige',
        'badge',
        'quality',
        'style',
        'look',
        'skin',
        ...b.extraDebrifyTvPlayerKeywords(),
      ],
    ),

    // --- Layout: Player Looks ---
    page(
      id: 'playerDock',
      row: SettingsRows.playerDock,
      category: kCatLayout,
      opener: b.openPlayerDock,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'playerDock',
        // The style is the primary choice; palette and size stay on the
        // page behind the More chip, and the preview honours them.
        options: [
          for (final c in kPlayerDockStyleChoices)
            LayoutOption(c.value, c.label, c.subtitle),
        ],
        // `two_tier` is the pre-arrangements value and means `auto`.
        current: () => b.layoutValues.playerDockStyle == 'two_tier'
            ? 'auto'
            : b.layoutValues.playerDockStyle,
        write: LayoutRowWriters.playerDockStyle,
        moreLabel: 'Colour & size',
        onMore: b.openPlayerDock,
        variant: () =>
            '${b.layoutValues.playerDockPalette}|'
            '${b.layoutValues.playerDockSize}',
      ),
      tv: false,
      phoneOrder: 310,
      desktopOrder: 310,
      phoneGroup: kGroupPlayerLooks,
      desktopGroup: kGroupPlayerLooks,
      visible: () => !b.isTelevision,
      subtitleOf: () => b.playerDockLabel,
      keywords: [
        'player',
        'controls',
        'dock',
        'buttons',
        'seekbar',
        'scrubber',
        'size',
        'colour',
        'color',
        'palette',
        'style',
        'look',
        'big',
        'small',
        'layout',
        'accent',
        ...b.extraPlayerDockKeywords(),
      ],
    ),
    page(
      id: 'tvPlayerControls',
      row: SettingsRows.tvPlayerControls,
      category: kCatLayout,
      opener: b.openTvPlayerControlsStyle,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 320,
      tvGroup: kGroupPlayerLooks,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? b.isAndroidTv : false,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvPlayerControlsStyleLabel,
      keywords: [
        'player',
        'controls',
        'dock',
        'buttons',
        'seekbar',
        'scrubber',
        'transport',
        'ott',
        'legacy',
        'cinema',
        'style',
        'look',
        'skin',
        ...b.extraTvPlayerControlsKeywords(),
      ],
    ),
    page(
      id: 'playLoaderStyle',
      row: SettingsRows.playLoaderStyle,
      category: kCatLayout,
      opener: b.openPlayLoaderStyle,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'playLoaderStyle',
        options: [
          for (final o in PlayLoaderStyleController.options)
            LayoutOption(o.id, o.label, o.blurb),
        ],
        current: () => b.layoutValues.playLoaderStyle,
        write: LayoutRowWriters.playLoaderStyle,
      ),
      phoneOrder: 330,
      desktopOrder: 330,
      tvOrder: 330,
      phoneGroup: kGroupPlayerLooks,
      desktopGroup: kGroupPlayerLooks,
      tvGroup: kGroupPlayerLooks,
      subtitleOf: () => b.playLoaderStyleLabel,
      keywords: [
        'play',
        'loading',
        'loader',
        'spinner',
        'searching',
        'resolving',
        'progress',
        'marquee',
        'backdrop',
        'logo',
        'stages',
        'pipeline',
        ...b.extraPlayLoaderKeywords(),
      ],
    ),

    // --- Layout: Screen ---
    page(
      id: 'tvScreenSize',
      row: SettingsRows.tvScreenSize,
      category: kCatLayout,
      opener: b.openTvScreenSize,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 410,
      tvGroup: kGroupScreen,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvUiScaleLabel,
      keywords: [
        'zoom',
        'zoomed in',
        'scale',
        'ui size',
        'text size',
        'font size',
        'bigger',
        'smaller',
        'density',
        'dpi',
        'resolution',
        'compact',
        'fit more',
        'display',
        ...b.extraTvScreenSizeKeywords(),
      ],
    ),
    page(
      id: 'tvRenderQuality',
      row: SettingsRows.tvRenderQuality,
      category: kCatLayout,
      opener: b.openTvRenderQuality,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 420,
      tvGroup: kGroupScreen,
      searchVisible: () => b.isAndroidTv,
      subtitleOf: () => b.tvRenderQualityLabel,
      keywords: [
        'stutter',
        'stuttering',
        'lag',
        'laggy',
        'jank',
        'janky',
        'choppy',
        'slow',
        'smooth',
        'smoothness',
        'performance',
        'fps',
        'frame rate',
        'speed',
        'scrolling',
        'resolution',
        'render',
        'rendering',
        '720p',
        '1080p',
        'sharp',
        'sharpness',
        'blurry',
        'soft',
        'quality',
        'gpu',
        'graphics',
        'display',
        ...b.extraTvRenderQualityKeywords(),
      ],
    ),
    page(
      id: 'tvHeroArtworkQuality',
      row: SettingsRows.tvHeroArtworkQuality,
      category: kCatLayout,
      opener: b.openTvHeroArtworkQuality,
      phone: false,
      desktop: false,
      tv: true,
      tvOrder: 430,
      tvGroup: kGroupScreen,
      searchVisible: () => b.isTelevision,
      subtitleOf: () => b.tvHeroArtworkQualityLabel,
      keywords: [
        'hero',
        'artwork',
        'image',
        'picture',
        'poster',
        'backdrop',
        'quality',
        'resolution',
        '1080p',
        'full hd',
        'sharp',
        'memory',
        'performance',
        'home',
        'tv',
        ...b.extraTvHeroArtworkKeywords(),
      ],
    ),

    // --- Theme ---
    page(
      id: 'looks',
      row: SettingsRows.looks,
      category: kCatTheme,
      opener: b.openLooks,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      subtitleOf: () => b.looksLabel,
      keywords: [
        'app',
        'theme',
        'app theme',
        'whole app',
        'colour',
        'color',
        'palette',
        'look',
        'style',
        'skin',
        'dark',
        'light',
        'legacy',
        'classic',
        'experimental',
        ...b.extraLooksKeywords(),
      ],
    ),
    // Merged appTheme (shipped) + detailTheme (deleted): appTheme
    // write-through-mirrors into detail_theme, so the two rows set the same
    // thing — appTheme survives, un-withheld, using its own dedicated
    // subtitle function (appThemeLabel).
    page(
      id: 'appTheme',
      row: SettingsRows.appTheme,
      category: kCatTheme,
      opener: b.openAppTheme,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      subtitleOf: () => b.appThemeLabel,
      keywords: const [
        'app',
        'theme',
        'details theme',
        'detail theme',
        'colour',
        'color',
        'palette',
        'look',
        'style',
        'skin',
        'dark',
        'light',
      ],
    ),
    page(
      id: 'themeTokens',
      row: SettingsRows.themeTokens,
      category: kCatTheme,
      opener: b.openThemeTokens,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      leafPageName: 'Advanced',
      subtitleOf: () => b.themeTokensLabel,
      keywords: const [
        'advanced',
        'token',
        'colour',
        'color',
        'accent',
        'background',
        'font',
        'corner',
        'motion',
      ],
    ),
    page(
      id: 'textBrightness',
      row: SettingsRows.textBrightness,
      category: kCatTheme,
      opener: b.openTextBrightness,
      phoneOrder: 40,
      desktopOrder: 40,
      tvOrder: 40,
      subtitleOf: () => b.textBrightnessLabel,
      keywords: [
        'text',
        'font',
        'color',
        'colour',
        'grey',
        'gray',
        'white',
        'dim',
        'dimmer',
        'brightness',
        'bright',
        'oled',
        'amoled',
        'contrast',
        'glare',
        'display',
        ...b.extraTextBrightnessKeywords(),
      ],
    ),
    page(
      id: 'launchAnimation',
      row: SettingsRows.launchAnimation,
      category: kCatTheme,
      opener: b.openLaunchAnimation,
      phoneOrder: 50,
      desktopOrder: 50,
      tvOrder: 50,
      subtitleOf: () => b.launchAnimationLabel,
      keywords: [
        'launch',
        'splash',
        'intro',
        'animation',
        'boot',
        'start',
        'startup',
        'logo',
        'ident',
        'opening',
        'neon',
        'chrome',
        'marquee',
        'prism',
        'monogram',
        'match app theme',
        'ident colour',
        'ident color',
        ...b.extraLaunchAnimationKeywords(),
      ],
    ),
    // Inline chips, not an opener: two choices do not earn a page, and a
    // remote should feel the change without leaving the pane. Search indexes
    // the two chips as leaves (settings_search_leaves.dart) rather than the
    // row, since there is nothing for a search hit to open.
    page(
      id: 'tvMotion',
      row: SettingsRows.tvMotion,
      category: kCatTheme,
      phone: false,
      desktop: false,
      tv: true,
      search: false,
      tvOrder: 60,
      searchVisible: () => b.isTelevision,
      kind: SettingsRowKind.options,
      layoutOptions: SettingsLayoutOptions(
        rowId: 'tvMotion',
        options: [
          for (final p in TvMotionProfile.values)
            LayoutOption(p.value, p.label, p.blurb),
        ],
        current: () =>
            (b.tvMotionProfile ?? TvMotionController.notifier).value.value,
        apply: (id) =>
            (b.selectTvMotionProfile ?? TvMotionController.select)(
              TvMotionProfile.fromPref(id)!,
            ),
      ),
    ),

    // --- Connections: Search & Playback ---
    page(
      id: 'player',
      row: SettingsRows.player,
      category: kCatConnections,
      opener: b.openExternalPlayer,
      phoneOrder: 250,
      desktopOrder: 250,
      tvOrder: 250,
      phoneGroup: kGroupSearchPlayback,
      desktopGroup: kGroupSearchPlayback,
      tvGroup: kGroupSearchPlayback,
      keywords: [
        'external player',
        'video player',
        if (b.isAndroid) ...['system app chooser', 'vlc', 'mx player'],
        'subtitle',
        'subtitles',
        'audio track',
        'skip intro',
        'skip credits',
        'outro',
        'auto provider',
        'skipdb',
        'introdb',
        'theintrodb',
        'watch history',
        'watched',
        'completion',
        'threshold',
        'movie',
        'episode',
        ...b.extraPlayerKeywords(),
      ],
    ),

    page(
      id: 'searchSettings',
      row: SettingsRows.searchSettings,
      category: kCatConnections,
      opener: b.openTorrentSettings,
      leafPageName: 'Engines',
      phoneOrder: 210,
      desktopOrder: 210,
      tvOrder: 210,
      phoneGroup: kGroupSearchPlayback,
      desktopGroup: kGroupSearchPlayback,
      tvGroup: kGroupSearchPlayback,
      keywords: const ['engines', 'sorting', 'torrent', 'sources'],
    ),
    page(
      id: 'filterSettings',
      row: SettingsRows.filterSettings,
      category: kCatConnections,
      opener: b.openFilterSettings,
      phoneOrder: 220,
      desktopOrder: 220,
      tvOrder: 220,
      phoneGroup: kGroupSearchPlayback,
      desktopGroup: kGroupSearchPlayback,
      tvGroup: kGroupSearchPlayback,
      keywords: const [
        'quality',
        'resolution',
        '1080p',
        '4k',
        '2160p',
        'hdr',
        'language',
        'codec',
        'hevc',
        'sdr',
        'dolby vision',
        'dynamic range',
      ],
    ),
    page(
      id: 'providerSettings',
      row: SettingsRows.providerSettings,
      category: kCatConnections,
      opener: b.openProviderSettings,
      phoneOrder: 230,
      desktopOrder: 230,
      tvOrder: 230,
      phoneGroup: kGroupSearchPlayback,
      desktopGroup: kGroupSearchPlayback,
      tvGroup: kGroupSearchPlayback,
      keywords: const [
        'default provider',
        'add torrent',
        'debrid',
        'ask every time',
        'show provider selection dialog',
        'torbox',
        'real-debrid',
        'premiumize',
        'alldebrid',
        'pikpak',
      ],
    ),
    page(
      id: 'quickPlay',
      row: SettingsRows.quickPlay,
      category: kCatConnections,
      opener: b.openQuickPlay,
      phoneOrder: 240,
      desktopOrder: 240,
      tvOrder: 240,
      phoneGroup: kGroupSearchPlayback,
      desktopGroup: kGroupSearchPlayback,
      tvGroup: kGroupSearchPlayback,
      keywords: const ['instant', 'auto play', 'one tap'],
    ),

    // --- Connections: IPTV ---
    page(
      id: 'iptvPlaylists',
      row: SettingsRows.iptvPlaylists,
      category: kCatConnections,
      opener: b.openIptv,
      phoneOrder: 310,
      desktopOrder: 310,
      tvOrder: 310,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const [
        'm3u',
        'xtream',
        'channels',
        'epg',
        'live tv',
        'playlist',
      ],
    ),
    page(
      id: 'debrifyTv',
      row: SettingsRows.debrifyTv,
      category: kCatConnections,
      opener: b.openDebrifyTv,
      phoneOrder: 350,
      desktopOrder: 350,
      tvOrder: 350,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const ['channels', 'limits', 'playback', 'android tv'],
    ),
    page(
      id: 'recordings',
      row: SettingsRows.recordings,
      category: kCatConnections,
      opener: b.openRecordings,
      phoneOrder: 360,
      desktopOrder: 360,
      tvOrder: 360,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const [
        'record',
        'recording',
        'recordings',
        'dvr',
        'schedule',
        'scheduled',
        'timer',
        'rec',
        'library',
        'capture',
        'iptv',
        'live tv',
      ],
    ),

    // --- Devices ---
    page(
      id: 'remote',
      row: SettingsRows.remote,
      category: kCatDevices,
      opener: b.openRemote,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      keywords: const ['cast', 'handoff', 'phone', 'receive', 'send', 'setup'],
    ),
    page(
      id: 'tvKeyboard',
      row: SettingsRows.tvKeyboard,
      category: kCatDevices,
      phone: true,
      desktop: false,
      tv: true,
      phoneOrder: 20,
      tvOrder: 20,
      kind: SettingsRowKind.toggle,
      visibleOn: (s) => s == SettingsLayoutSurface.tv ? true : b.isAndroidTv,
      toggleValue: () => b.tvKeyboardEnabled,
      onToggle: b.onToggleTvKeyboard,
      keywords: const [
        'on-screen keyboard',
        'remote',
        'text input',
        'ime',
        'typing',
        'voice',
        'mic',
        'microphone',
        'dictation',
        'speak',
      ],
    ),

    // --- Profiles ---
    page(
      id: 'switchProfile',
      row: SettingsRows.switchProfile,
      category: kCatProfiles,
      opener: b.openSwitchProfile,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'profile',
        'profiles',
        'switch',
        'switch to this profile',
        'who is watching',
        'avatar',
        'pin',
        'kids',
        'account',
        'startup',
        'always ask',
        'household',
        'backup',
        'restore',
        'send to tv',
        'transfer',
        'delete profile',
        'disable profile',
      ],
    ),
    page(
      id: 'addProfile',
      row: SettingsRows.addProfile,
      category: kCatProfiles,
      opener: b.openAddProfile,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'create profile',
        'new profile',
        'add user',
        'kid',
        'member',
        'admin',
        'start from my settings',
        'copy appearance and playback defaults',
        'search by title',
        'keyword search',
        'debrify tv',
        'stremio tv',
        'live tv',
        'youtube',
        'download and record',
        'remote',
        'manage own sources',
        'cloud files',
      ],
    ),
    page(
      id: 'editProfile',
      row: SettingsRows.editProfile,
      category: kCatProfiles,
      opener: b.openEditProfile,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      visible: () => b.showSwitchProfile,
      keywords: const [
        'rename',
        'avatar',
        'pin',
        'access',
        'permissions',
        'edit user',
        'save name and avatar',
        'choose image',
        'gif',
        'set pin',
        'change pin',
        'remove pin',
        'pin protection',
        'lock when the app resumes',
        'auto-lock',
        'after 5 minutes',
        'after 15 minutes',
        'after 30 minutes',
        'after 1 hour',
        'copy appearance and playback defaults',
        'role',
        'admin',
        'member',
        'kid',
        'pages and abilities',
        'keyword search',
        'live tv',
        'youtube',
        'download and record',
        'manage own sources',
        'cloud files',
        'torrent engines',
        'debrid and cloud',
        'addons',
        'trackers and lists',
        'live tv and indexers',
        'transfer ownership',
        'diagnostics',
        're-run the questions',
        'full editor',
      ],
    ),
    page(
      id: 'profileAppearance',
      row: SettingsRows.profileAppearance,
      category: kCatProfiles,
      opener: b.openProfileAppearance,
      kind: SettingsRowKind.options,
      layoutOptions: layouts(
        rowId: 'profileAppearance',
        options: [
          for (final o in ProfileGateStyle.options)
            LayoutOption(o.id, o.label, o.blurb),
        ],
        current: () => b.layoutValues.profileGateStyle,
        write: LayoutRowWriters.profileGateStyle,
        // Apple TV keeps the Personalized Top Shelf toggle on the page.
        moreLabel: b.isTvOS ? 'Top Shelf' : null,
        onMore: b.isTvOS ? b.openProfileAppearance : null,
      ),
      phoneOrder: 40,
      desktopOrder: 40,
      tvOrder: 40,
      leafPageName: 'Profile Picker',
      subtitleOf: () => b.profileAppearanceLabel,
      keywords: [
        'profile',
        'picker',
        'who is watching',
        'who\'s watching',
        'marquee',
        'theater',
        'portrait wall',
        'top shelf',
        'personalized top shelf',
        'apple tv',
        ...b.extraProfileAppearanceKeywords(),
      ],
    ),

    // --- Data & Backup ---
    page(
      id: 'downloadLocation',
      row: SettingsRows.downloadLocation,
      category: kCatData,
      opener: b.openDownloadLocation,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      desktopGroup: kGroupDownloads,
      tvGroup: kGroupDownloads,
      visible: () => b.downloadLocationSupported,
      subtitleOf: () => b.downloadLocationSubtitle,
      keywords: const [
        'sd card',
        'folder',
        'external storage',
        'saf',
        'location',
        'path',
        'directory',
        'sd',
        'choose folder',
        'reset to default',
        'another drive',
      ],
    ),
    page(
      id: 'clearDownloads',
      row: SettingsRows.clearDownloads,
      category: kCatData,
      opener: b.clearDownloads,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      desktopGroup: kGroupMaintenance,
      tvGroup: kGroupMaintenance,
      keywords: const ['queue', 'history', 'clear', 'remove'],
    ),
    page(
      id: 'clearPlayback',
      row: SettingsRows.clearPlayback,
      category: kCatData,
      opener: b.clearPlayback,
      phoneOrder: 30,
      desktopOrder: 30,
      tvOrder: 30,
      desktopGroup: kGroupMaintenance,
      tvGroup: kGroupMaintenance,
      keywords: const [
        'resume',
        'watch history',
        'reset progress',
        'continue watching',
      ],
    ),
    page(
      id: 'createBackup',
      row: SettingsRows.createBackup,
      category: kCatData,
      opener: b.createBackup,
      phoneOrder: 40,
      desktopOrder: 40,
      tvOrder: 40,
      desktopGroup: kGroupBackup,
      tvGroup: kGroupBackup,
      keywords: const [
        'export',
        'save',
        'addons',
        'search engines',
        'all profiles',
        'shared connections',
        'encrypted',
        'password',
        'passphrase',
        'minimum 8 characters',
        'recovery code',
      ],
    ),
    page(
      id: 'restoreBackup',
      row: SettingsRows.restoreBackup,
      category: kCatData,
      opener: b.restoreBackup,
      phoneOrder: 50,
      desktopOrder: 50,
      tvOrder: 50,
      desktopGroup: kGroupBackup,
      tvGroup: kGroupBackup,
      keywords: const [
        'import',
        'load',
        'encrypted',
        'password',
        'passphrase',
        'unlock backup',
        'admin pin',
        'confirm admin pin',
        'profiles',
        'connections',
      ],
    ),
    page(
      id: 'exportDiagnosticLogs',
      row: SettingsRows.exportDiagnosticLogs,
      category: kCatData,
      opener: b.exportDiagnosticLogs,
      phoneOrder: 60,
      desktopOrder: 60,
      tvOrder: 60,
      desktopGroup: kGroupDiagnostics,
      tvGroup: kGroupDiagnostics,
      visible: () => b.diagnosticExportVisible,
      keywords: const [
        'logs',
        'diagnostics',
        'debug',
        'crash',
        'support',
        'android tv',
        'last two hours',
      ],
    ),

    // --- About ---
    page(
      id: 'autoUpdate',
      row: SettingsRows.autoUpdate,
      category: kCatAbout,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      kind: SettingsRowKind.toggle,
      toggleValue: () => b.autoUpdateChecksEnabled,
      onToggle: b.onToggleAutoUpdateChecks,
      keywords: const ['notify', 'releases', 'startup'],
    ),
    page(
      id: 'checkUpdates',
      row: SettingsRows.checkUpdates,
      category: kCatAbout,
      opener: b.checkUpdates,
      phoneOrder: 20,
      desktopOrder: 20,
      tvOrder: 20,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      subtitleOf: () => b.updateSubtitle,
      tag: 'New',
      trailingOf: () => b.checkingUpdates
          ? const SizedBox(
              width: 20,
              height: 20,
              child: CircularProgressIndicator(strokeWidth: 2.5),
            )
          : null,
      keywords: const ['version', 'upgrade', 'github', 'new build'],
    ),
    page(
      id: 'version',
      row: SettingsRows.version,
      category: kCatAbout,
      phoneOrder: 70,
      desktopOrder: 30,
      tvOrder: 30,
      desktopGroup: kGroupUpdates,
      tvGroup: kGroupUpdates,
      kind: SettingsRowKind.info,
      search: false,
      subtitleOf: () => b.appVersion,
    ),
    page(
      id: 'supportDonation',
      row: SettingsRows.supportDebrify,
      category: kCatAbout,
      opener: b.openSupportDonation,
      phoneOrder: 30,
      desktopOrder: 40,
      tvOrder: 40,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      visible: () => b.showSupportDonation,
      titleOf: () => b.supportDonationLabel,
      subtitleOf: () => b.supportDonationSubtitle,
      keywords: const ['donate', 'tip', 'contribute', 'fund'],
    ),
    page(
      id: 'reddit',
      row: SettingsRows.reddit,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.reddit.url!),
      phoneOrder: 40,
      desktopOrder: 50,
      tvOrder: 50,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['community', 'subreddit'],
    ),
    page(
      id: 'discord',
      row: SettingsRows.discord,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.discord.url!),
      phoneOrder: 50,
      desktopOrder: 60,
      tvOrder: 60,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['community', 'chat', 'help'],
    ),
    page(
      id: 'github',
      row: SettingsRows.github,
      category: kCatAbout,
      opener: () => launchSettingsUrl(SettingsRows.github.url!),
      phoneOrder: 60,
      desktopOrder: 70,
      tvOrder: 70,
      desktopGroup: kGroupCommunity,
      tvGroup: kGroupCommunity,
      kind: SettingsRowKind.url,
      keywords: const ['source code', 'contribute', 'issues'],
    ),

    // --- Danger Zone ---
    page(
      id: 'resetDebrify',
      row: SettingsRows.resetDebrify,
      category: kCatDanger,
      opener: b.resetApp,
      phoneOrder: 10,
      desktopOrder: 10,
      tvOrder: 10,
      destructive: true,
      keywords: const ['wipe', 'factory reset', 'clear all', 'erase'],
    ),

    // --- Search-only destinations (not root rows) ---
    page(
      id: 'addons',
      row: const SettingsRowContent(
        icon: Icons.extension_rounded,
        title: 'Addons',
        subtitle: 'Stremio addons and torrent search engines',
      ),
      category: kCatAddons,
      opener: b.openAddons,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'addon',
        'addons',
        'stremio',
        'manifest',
        'install',
        'catalog',
        'catalogs',
        'subtitles',
        'torrentio',
        'marketplace',
        'engine',
        'engines',
        'import',
        'yaml',
        'add engine',
        'import from file',
        'remove addon',
        'delete all addons',
        'view details',
        'resources',
        'id prefixes',
        'last checked',
      ],
    ),
    page(
      id: 'stremioTv',
      row: const SettingsRowContent(
        icon: Icons.smart_display_rounded,
        title: 'Stremio TV',
        subtitle: 'Rotation, quality, provider and playback for Stremio TV',
      ),
      category: kCatStremioTv,
      opener: b.openStremioTv,
      phone: false,
      desktop: false,
      tv: false,
      search: true,
      keywords: const [
        'stremio tv',
        'channel',
        'channels',
        'rotation',
        'series rotation',
        'random',
        'episodes',
        'quality',
        'debrid provider',
        'torrents first',
        'auto-refresh',
        'now playing',
        'start position',
      ],
    ),
    page(
      id: 'iptvLists',
      row: const SettingsRowContent(
        icon: Icons.bookmark_rounded,
        title: 'IPTV lists',
        subtitle: 'Create and manage your channel lists',
      ),
      category: kCatConnections,
      opener: b.openIptv,
      phoneOrder: 320,
      desktopOrder: 320,
      tvOrder: 320,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const [
        'list',
        'lists',
        'favorites',
        'favourites',
        'saved channels',
        'iptv',
        'collection',
      ],
    ),
    page(
      id: 'startupChannel',
      row: const SettingsRowContent(
        icon: Icons.live_tv_rounded,
        title: 'Startup channel',
        subtitle: 'Open straight into a live channel when the app starts',
      ),
      category: kCatConnections,
      opener: b.openIptv,
      phoneOrder: 330,
      desktopOrder: 330,
      tvOrder: 330,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const [
        'startup',
        'start up',
        'boot',
        'launch',
        'auto play',
        'autoplay',
        'auto launch',
        'last watched',
        'on open',
        'iptv',
        'live tv',
      ],
    ),
    page(
      id: 'iptvContinueWatching',
      row: const SettingsRowContent(
        icon: Icons.history_toggle_off_rounded,
        title: 'IPTV continue watching',
        subtitle: 'Track the movies and series you start on IPTV',
      ),
      category: kCatConnections,
      opener: b.openIptv,
      phoneOrder: 340,
      desktopOrder: 340,
      tvOrder: 340,
      phoneGroup: kGroupIptv,
      desktopGroup: kGroupIptv,
      tvGroup: kGroupIptv,
      keywords: const [
        'continue watching',
        'continue',
        'resume',
        'history',
        'watch history',
        'track',
        'tracking',
        'shelf',
        'iptv',
        'vod',
        'movies',
        'series',
      ],
    ),

    // --- Connections: Storage Providers ---
    page(
      id: 'realDebrid',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'Real-Debrid',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openRealDebrid,
      phoneOrder: 110,
      desktopOrder: 110,
      tvOrder: 110,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.realDebridSubtitle,
      keywords: const [
        'debrid',
        'real-debrid',
        'rd',
        'premium',
        'api key',
        'add api key',
        'logout',
        'login',
        'account',
        'integration',
      ],
    ),
    page(
      id: 'torbox',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'TorBox',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openTorbox,
      phoneOrder: 120,
      desktopOrder: 120,
      tvOrder: 120,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.torboxSubtitle,
      keywords: const [
        'debrid',
        'premium',
        'api key',
        'add api key',
        'logout',
        'login',
        'account',
        'integration',
      ],
    ),
    page(
      id: 'premiumize',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'Premiumize',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openPremiumize,
      phoneOrder: 130,
      desktopOrder: 130,
      tvOrder: 130,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.premiumizeSubtitle,
      keywords: const [
        'debrid',
        'premium',
        'api key',
        'add api key',
        'logout',
        'login',
        'account',
        'integration',
      ],
    ),
    page(
      id: 'allDebrid',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'AllDebrid',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openAllDebrid,
      phoneOrder: 140,
      desktopOrder: 140,
      tvOrder: 140,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.allDebridSubtitle,
      keywords: const [
        'debrid',
        'ad',
        'premium',
        'api key',
        'add api key',
        'logout',
        'login',
        'account',
        'integration',
      ],
    ),
    page(
      id: 'pikpak',
      row: const SettingsRowContent(
        icon: Icons.link_rounded,
        title: 'PikPak',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openPikPak,
      phoneOrder: 150,
      desktopOrder: 150,
      tvOrder: 150,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.pikpakSubtitle,
      keywords: const [
        'cloud',
        'storage',
        'login',
        'account',
        'email',
        'password',
        'logout',
        'change account',
        'remove account',
        'integration',
      ],
    ),
    page(
      id: 'webDav',
      row: const SettingsRowContent(
        icon: Icons.cloud_rounded,
        title: 'WebDAV',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openWebDav,
      phoneOrder: 160,
      desktopOrder: 160,
      tvOrder: 160,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.webDavSubtitle,
      keywords: const [
        'cloud',
        'nas',
        'server',
        'seedbox',
        'url',
        'username',
        'password',
        'app token',
        'integration',
      ],
    ),
    page(
      id: 'indexerManagers',
      row: const SettingsRowContent(
        icon: Icons.manage_search_rounded,
        title: 'Indexer Managers',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openIndexerManagers,
      phoneOrder: 170,
      desktopOrder: 170,
      tvOrder: 170,
      phoneGroup: kGroupStorageProviders,
      desktopGroup: kGroupStorageProviders,
      tvGroup: kGroupStorageProviders,
      subtitleOf: () => b.indexerManagersSubtitle,
      keywords: const [
        'indexer',
        'torznab',
        'jackett',
        'prowlarr',
        'engines',
        'integration',
      ],
    ),

    // --- Connections: Tracking ---
    page(
      id: 'tracking',
      row: const SettingsRowContent(
        icon: Icons.sync_alt_rounded,
        title: 'Tracking',
        subtitle: 'Scrobble, progress source & Home ticks',
      ),
      category: kCatConnections,
      opener: b.openTracking,
      phoneOrder: 410,
      desktopOrder: 410,
      tvOrder: 410,
      phoneGroup: kGroupTracking,
      desktopGroup: kGroupTracking,
      tvGroup: kGroupTracking,
      keywords: const [
        'scrobble',
        'sync catalog',
        'watch progress',
        'continue watching source',
        'home ticks',
      ],
    ),
    page(
      id: 'trakt',
      row: const SettingsRowContent(
        icon: Icons.sync_rounded,
        title: 'Trakt',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openTrakt,
      phoneOrder: 420,
      desktopOrder: 420,
      tvOrder: 420,
      phoneGroup: kGroupTracking,
      desktopGroup: kGroupTracking,
      tvGroup: kGroupTracking,
      subtitleOf: () => b.traktSubtitle,
      keywords: const [
        'scrobble',
        'sync',
        'watch history',
        'watchlist',
        'login',
        'activate',
        'device code',
        'logout',
      ],
    ),
    page(
      id: 'simkl',
      row: const SettingsRowContent(
        icon: Icons.sync_rounded,
        title: 'Simkl',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openSimkl,
      phoneOrder: 430,
      desktopOrder: 430,
      tvOrder: 430,
      phoneGroup: kGroupTracking,
      desktopGroup: kGroupTracking,
      tvGroup: kGroupTracking,
      subtitleOf: () => b.simklSubtitle,
      keywords: const [
        'scrobble',
        'sync',
        'watch history',
        'login',
        'pin',
        'device code',
        'logout',
      ],
    ),
    page(
      id: 'mdblist',
      row: const SettingsRowContent(
        icon: Icons.list_alt_rounded,
        title: 'MDBList',
        subtitle: '',
      ),
      category: kCatConnections,
      opener: b.openMdblist,
      phoneOrder: 440,
      desktopOrder: 440,
      tvOrder: 440,
      phoneGroup: kGroupTracking,
      desktopGroup: kGroupTracking,
      tvGroup: kGroupTracking,
      subtitleOf: () => b.mdblistSubtitle,
      visible: () => b.mdblistEnabled,
      keywords: const ['lists', 'ratings'],
    ),
  ];
}

SettingsPageRegistry productionSettingsRegistry(SettingsPageBindings b) =>
    SettingsPageRegistry(pages: buildSettingsPages(b));
